-- community_guides: user-written god / role guides (mirrors contributor_builds patterns: username + timestamps + RLS via current_app_username)
-- Run in Supabase SQL Editor after user_data / certification_requests exist.
-- Featured vs Community is driven by server: author_is_featured is set on INSERT from certification + user_data.featured_creator.

-- optional updated_at helper (separate from contributor_builds trigger name)
create or replace function public.set_updated_at_community_guides()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Server decides Featured bucket (same notion as “featured contributors” elsewhere)
create or replace function public.community_guides_set_author_featured()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_feat boolean;
begin
  select (
    exists (
      select 1
      from public.certification_requests cr
      where cr.username = new.username
        and cr.status = 'approved'
    )
    or exists (
      select 1
      from public.user_data u
      where u.username = new.username
        and coalesce(u.featured_creator, false)
    )
  )
  into v_feat;
  new.author_is_featured := coalesce(v_feat, false);
  return new;
end;
$$;

create table if not exists public.community_guides (
  id bigint generated by default as identity not null,
  username text not null,
  author_display_name text null,
  guide_type text not null,
  title text not null,
  subtitle text null,
  body text null,
  god_name text null,
  god_internal_name text null,
  role_lane text null,
  patch text null,
  author_is_featured boolean not null default false,
  upvotes integer not null default 0,
  extra jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint community_guides_pkey primary key (id),
  constraint community_guides_guide_type_check check (guide_type = any (array['god'::text, 'role'::text]))
) tablespace pg_default;

drop trigger if exists community_guides_set_updated_at on public.community_guides;
create trigger community_guides_set_updated_at
before update on public.community_guides
for each row
execute function public.set_updated_at_community_guides();

drop trigger if exists trg_community_guides_set_author_featured on public.community_guides;
create trigger trg_community_guides_set_author_featured
before insert on public.community_guides
for each row
execute function public.community_guides_set_author_featured();

alter table public.community_guides enable row level security;

drop policy if exists community_guides_read_all on public.community_guides;
create policy community_guides_read_all
on public.community_guides for select
to public
using (true);

drop policy if exists community_guides_owner_write on public.community_guides;
create policy community_guides_owner_write
on public.community_guides for all
to public
using (username = public.current_app_username())
with check (username = public.current_app_username());

-- Match contributor_builds update pattern when session uses custom login + set_current_user
create or replace function public.update_community_guide(
  guide_id bigint,
  request_username text,
  payload jsonb
)
returns setof public.community_guides
language plpgsql
security definer
set search_path = public
as $$
begin
  perform set_config('app.current_user', request_username, true);
  return query
  update public.community_guides g
  set
    title = coalesce(nullif(payload ->> 'title', ''), g.title),
    subtitle = case when payload ? 'subtitle' then nullif(payload ->> 'subtitle', '') else g.subtitle end,
    body = coalesce(nullif(payload ->> 'body', ''), g.body),
    guide_type = coalesce(nullif(payload ->> 'guide_type', ''), g.guide_type),
    god_name = case when payload ? 'god_name' then nullif(payload ->> 'god_name', '') else g.god_name end,
    god_internal_name = case when payload ? 'god_internal_name' then nullif(payload ->> 'god_internal_name', '') else g.god_internal_name end,
    role_lane = case when payload ? 'role_lane' then nullif(payload ->> 'role_lane', '') else g.role_lane end,
    patch = case when payload ? 'patch' then nullif(payload ->> 'patch', '') else g.patch end,
    author_display_name = case
      when payload ? 'author_display_name' then nullif(payload ->> 'author_display_name', '')
      else g.author_display_name
    end,
    updated_at = now()
  where g.id = guide_id
    and g.username = request_username
  returning *;
end;
$$;

grant execute on function public.update_community_guide(bigint, text, jsonb) to anon, authenticated, service_role;
