// Script to convert HTML file to JS module
const fs = require('fs');
const path = require('path');

const htmlPath = path.join(__dirname, 'app', 'Interactive Conquest Map (1).html');const outputPath = path.join(__dirname, 'data', '_conquestMapHtml.js');

try {
  const htmlContent = fs.readFileSync(htmlPath, 'utf8');
  
  // Escape backticks and template literal syntax
  const escaped = htmlContent
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\${/g, '\\${');
  
  const jsContent = `// Auto-generated from Interactive Conquest Map (1).html
// Do not edit this file directly - edit the HTML file and regenerate

export const conquestMapHtml = \`${escaped}\`;
`;

  fs.writeFileSync(outputPath, jsContent, 'utf8');
  console.log('Successfully converted HTML to JS module!');
  console.log(`Output: ${outputPath}`);
} catch (error) {
  console.error('Error converting HTML file:', error);
  process.exit(1);
}

