
// Local item icons loaded from `app/data/Icons/Item Icons`
// Keyed by the original JSON basename (e.g. "SoulGem.webp")
const itemIconMap = {
  'AdamantineSickle.webp': require('./data/Icons/Item Icons/AdamantineSickle.webp'),
  'AegisOfAcceleration.webp': require('./data/Icons/Item Icons/AegisOfAcceleration.webp'),
  'Ancile.webp': require('./data/Icons/Item Icons/Ancile.webp'),
  'ArchmagesGem.webp': require('./data/Icons/Item Icons/ArchmagesGem.webp'),
  'Arondight.webp': require('./data/Icons/Item Icons/Arondight.webp'),
  'AtalantasBow.webp': require('./data/Icons/Item Icons/AtalantasBow.webp'),
  'AvatarsParashu.webp': require('./data/Icons/Item Icons/AvatarsParashu.webp'),
  'BalorsEye.webp': require('./data/Icons/Item Icons/BalorsEye.webp'),
  'BancroftsTalon.webp': require('./data/Icons/Item Icons/BancroftsTalon.webp'),
  'BanefulRapier.webp': require('./data/Icons/Item Icons/BanefulRapier.webp'),
  'BerserkersShield.webp': require('./data/Icons/Item Icons/BerserkersShield.webp'),
  'BindingsOfLyngvi.webp': require('./data/Icons/Item Icons/BindingsOfLyngvi.webp'),
  'BlinkRune.webp': require('./data/Icons/Item Icons/BlinkRune.webp'),
  'Blood-BoundBook.webp': require('./data/Icons/Item Icons/Blood-BoundBook.webp'),
  'BloodForge.webp': require('./data/Icons/Item Icons/BloodForge.webp'),
  'BlueStoneBrooch.webp': require('./data/Icons/Item Icons/BlueStoneBrooch.webp'),
  'BlueStonePendant.webp': require('./data/Icons/Item Icons/BlueStonePendant.webp'),
  'BookOfThoth.webp': require('./data/Icons/Item Icons/BookOfThoth.webp'),
  'Bow.webp': require('./data/Icons/Item Icons/Bow.webp'),
  'BragisHarp.webp': require('./data/Icons/Item Icons/BragisHarp.webp'),
  'BrawlersRuin.webp': require('./data/Icons/Item Icons/BrawlersRuin.webp'),
  'BreastplateOfValor.webp': require('./data/Icons/Item Icons/BreastplateOfValor.webp'),
  'BumbasCudgel.webp': require('./data/Icons/Item Icons/BumbasCudgel.webp'),
  'BumbasGoldenDagger.webp': require('./data/Icons/Item Icons/BumbasGoldenDagger.webp'),
  'BumbasHammer.webp': require('./data/Icons/Item Icons/BumbasHammer.webp'),
  'BumbasSpear.webp': require('./data/Icons/Item Icons/BumbasSpear.webp'),
  'Caestus.webp': require('./data/Icons/Item Icons/Caestus.webp'),
  'ChronosPendant.webp': require('./data/Icons/Item Icons/ChronosPendant.webp'),
  'CircesHexstone.webp': require('./data/Icons/Item Icons/CircesHexstone.webp'),
  'CircleofProtection.webp': require('./data/Icons/Item Icons/CircleofProtection.webp'),
  'Circlet.webp': require('./data/Icons/Item Icons/Circlet.webp'),
  'ConduitGem.webp': require('./data/Icons/Item Icons/ConduitGem.webp'),
  'DaggerOfFrenzy.webp': require('./data/Icons/Item Icons/DaggerOfFrenzy.webp'),
  'DeathMetal.webp': require('./data/Icons/Item Icons/DeathMetal.webp'),
  'Deathbringer.webp': require('./data/Icons/Item Icons/Deathbringer.webp'),
  'DeathsEmbrace.webp': require('./data/Icons/Item Icons/DeathsEmbrace.webp'),
  'DeathsToll.webp': require('./data/Icons/Item Icons/DeathsToll.webp'),
  'DevourersGauntlet.webp': require('./data/Icons/Item Icons/DevourersGauntlet.webp'),
  'DivineRuin.webp': require('./data/Icons/Item Icons/DivineRuin.webp'),
  'DoomOrb.webp': require('./data/Icons/Item Icons/DoomOrb.webp'),
  'DreamersIdol.webp': require('./data/Icons/Item Icons/DreamersIdol.webp'),
  'EldritchOrb.webp': require('./data/Icons/Item Icons/EldritchOrb.webp'),
  'EyeOfProvidence.webp': require('./data/Icons/Item Icons/EyeOfProvidence.webp'),
  'EyeOfTheStorm.webp': require('./data/Icons/Item Icons/EyeOfTheStorm.webp'),
  'Gem.webp': require('./data/Icons/Item Icons/Gem.webp'),
  'GemOfFocus.webp': require('./data/Icons/Item Icons/GemOfFocus.webp'),
  'GemOfIsolation.webp': require('./data/Icons/Item Icons/GemOfIsolation.webp'),
  'GenjisGuard.webp': require('./data/Icons/Item Icons/GenjisGuard.webp'),
  'GloriousPridwen.webp': require('./data/Icons/Item Icons/GloriousPridwen.webp'),
  'HandOfTheAbyss.webp': require('./data/Icons/Item Icons/HandOfTheAbyss.webp'),
  'Heartseeker.webp': require('./data/Icons/Item Icons/Heartseeker.webp'),
  'HelmOfDarkness.webp': require('./data/Icons/Item Icons/HelmOfDarkness.webp'),
  'HelmOfRadiance.webp': require('./data/Icons/Item Icons/HelmOfRadiance.webp'),
  'Heroism.webp': require('./data/Icons/Item Icons/Heroism.webp'),
  'HideOfNemean.webp': require('./data/Icons/Item Icons/HideOfNemean.webp'),
  'HuntersCowl.webp': require('./data/Icons/Item Icons/HuntersCowl.webp'),
  'HussarsWings.webp': require('./data/Icons/Item Icons/HussarsWings.webp'),
  'HydrasLament.webp': require('./data/Icons/Item Icons/HydrasLament.webp'),
  'InfusedAxe.webp': require('./data/Icons/Item Icons/InfusedAxe.webp'),
  'JadeScepter.webp': require('./data/Icons/Item Icons/JadeScepter.webp'),
  'JotunnsRevenge.webp': require('./data/Icons/Item Icons/JotunnsRevenge.webp'),
  'Kopesh.webp': require('./data/Icons/Item Icons/Kopesh.webp'),
  'LeatherCowl.webp': require('./data/Icons/Item Icons/LeatherCowl.webp'),
  'LernaeanBow.webp': require('./data/Icons/Item Icons/LernaeanBow.webp'),
  'LevianthansHide.webp': require('./data/Icons/Item Icons/LevianthansHide.webp'),
  'LifeBinder.webp': require('./data/Icons/Item Icons/LifeBinder.webp'),
  'LorgMor.webp': require('./data/Icons/Item Icons/LorgMor.webp'),
  'MagisCloak.webp': require('./data/Icons/Item Icons/MagisCloak.webp'),
  'ManaPotion.webp': require('./data/Icons/Item Icons/ManaPotion.webp'),
  'ManchuBow.webp': require('./data/Icons/Item Icons/ManchuBow.webp'),
  'MantleOfDiscord.webp': require('./data/Icons/Item Icons/MantleOfDiscord.webp'),
  'Medallion.webp': require('./data/Icons/Item Icons/Medallion.webp'),
  'MeteorHammer.webp': require('./data/Icons/Item Icons/MeteorHammer.webp'),
  'MusashisDualSwords.webp': require('./data/Icons/Item Icons/MusashisDualSwords.webp'),
  'MysticalMail.webp': require('./data/Icons/Item Icons/MysticalMail.webp'),
  'Necronomicon.webp': require('./data/Icons/Item Icons/Necronomicon.webp'),
  'ObsidianMacuahuitl.webp': require('./data/Icons/Item Icons/ObsidianMacuahuitl.webp'),
  'OdysseusBow.webp': require('./data/Icons/Item Icons/OdysseusBow.webp'),
  'OlmecBlue.webp': require('./data/Icons/Item Icons/OlmecBlue.webp'),
  'OniHuntersGarb.webp': require('./data/Icons/Item Icons/OniHuntersGarb.webp'),
  'OracleStaff.webp': require('./data/Icons/Item Icons/OracleStaff.webp'),
  'PendulumBlade.webp': require('./data/Icons/Item Icons/PendulumBlade.webp'),
  'PendulumOfTheAges.webp': require('./data/Icons/Item Icons/PendulumOfTheAges.webp'),
  'PhantomShell.webp': require('./data/Icons/Item Icons/PhantomShell.webp'),
  'PharaohsCurse.webp': require('./data/Icons/Item Icons/PharaohsCurse.webp'),
  'PhoenixAmulet.webp': require('./data/Icons/Item Icons/PhoenixAmulet.webp'),
  'Polynomicon.webp': require('./data/Icons/Item Icons/Polynomicon.webp'),
  'PropheticCloak.webp': require('./data/Icons/Item Icons/PropheticCloak.webp'),
  'PurificationBeads.webp': require('./data/Icons/Item Icons/PurificationBeads.webp'),
  'QinsBlade.webp': require('./data/Icons/Item Icons/QinsBlade.webp'),
  'Rage.webp': require('./data/Icons/Item Icons/Rage.webp'),
  'Reliquary.webp': require('./data/Icons/Item Icons/Reliquary.webp'),
  'RestorativeAmanita.webp': require('./data/Icons/Item Icons/RestorativeAmanita.webp'),
  'Ring.webp': require('./data/Icons/Item Icons/Ring.webp'),
  'RingOfDispel.webp': require('./data/Icons/Item Icons/RingOfDispel.webp'),
  'RipTalon.webp': require('./data/Icons/Item Icons/RipTalon.webp'),
  'Rune.webp': require('./data/Icons/Item Icons/Rune.webp'),
  'Sabre.webp': require('./data/Icons/Item Icons/Sabre.webp'),
  'SandsOfTime.webp': require('./data/Icons/Item Icons/SandsOfTime.webp'),
  'Sash.webp': require('./data/Icons/Item Icons/Sash.webp'),
  'ScepterOfDominion.webp': require('./data/Icons/Item Icons/ScepterOfDominion.webp'),
  'ScreechingGargoyle.webp': require('./data/Icons/Item Icons/ScreechingGargoyle.webp'),
  'Scythe.webp': require('./data/Icons/Item Icons/Scythe.webp'),
  'Selflessness.webp': require('./data/Icons/Item Icons/Selflessness.webp'),
  'SerpentSpear.webp': require('./data/Icons/Item Icons/SerpentSpear.webp'),
  'SharpshootersArrow.webp': require('./data/Icons/Item Icons/SharpshootersArrow.webp'),
  'Shield.webp': require('./data/Icons/Item Icons/Shield.webp'),
  'ShieldOfThePhoenix.webp': require('./data/Icons/Item Icons/ShieldOfThePhoenix.webp'),
  'ShiftersShieldV2.webp': require('./data/Icons/Item Icons/ShiftersShieldV2.webp'),
  'SoulDevourer.webp': require('./data/Icons/Item Icons/SoulDevourer.webp'),
  'SoulGem.webp': require('./data/Icons/Item Icons/SoulGem.webp'),
  'SpeareOfDesolation.webp': require('./data/Icons/Item Icons/SpeareOfDesolation.webp'),
  'SphereOfNegation.webp': require('./data/Icons/Item Icons/SphereOfNegation.webp'),
  'SpiritRobe.webp': require('./data/Icons/Item Icons/SpiritRobe.webp'),
  'StaffOfCosmicHorror.webp': require('./data/Icons/Item Icons/StaffOfCosmicHorror.webp'),
  'SurvivorsSash.webp': require('./data/Icons/Item Icons/SurvivorsSash.webp'),
  'TalismanOfPurification.webp': require('./data/Icons/Item Icons/TalismanOfPurification.webp'),
  'TekkoKagi.webp': require('./data/Icons/Item Icons/TekkoKagi.webp'),
  'TheCrusher.webp': require('./data/Icons/Item Icons/TheCrusher.webp'),
  'TheExecutioner.webp': require('./data/Icons/Item Icons/TheExecutioner.webp'),
  'TheNemes.webp': require('./data/Icons/Item Icons/TheNemes.webp'),
  'TheReaper.webp': require('./data/Icons/Item Icons/TheReaper.webp'),
  'TheWorldStone.webp': require('./data/Icons/Item Icons/TheWorldStone.webp'),
  'TotemOfDeath.webp': require('./data/Icons/Item Icons/TotemOfDeath.webp'),
  'TritonsConch.webp': require('./data/Icons/Item Icons/TritonsConch.webp'),
  'Tyrfing.webp': require('./data/Icons/Item Icons/Tyrfing.webp'),
  'VoidShield.webp': require('./data/Icons/Item Icons/VoidShield.webp'),
  'VoidStone.webp': require('./data/Icons/Item Icons/VoidStone.webp'),
  'WarBanner.webp': require('./data/Icons/Item Icons/WarBanner.webp'),
  'WarFlag.webp': require('./data/Icons/Item Icons/WarFlag.webp'),
  'Wish-GrantingPearl.webp': require('./data/Icons/Item Icons/Wish-GrantingPearl.webp'),
  'YogisNecklace.webp': require('./data/Icons/Item Icons/YogisNecklace.webp'),
  'agilityRelic.webp': require('./data/Icons/Item Icons/agilityRelic.webp'),
  'aladdinsLamp.webp': require('./data/Icons/Item Icons/aladdinsLamp.webp'),
  'ancientSignet.webp': require('./data/Icons/Item Icons/ancientSignet.webp'),
  'avengingBlade.webp': require('./data/Icons/Item Icons/avengingBlade.webp'),
  'axe.webp': require('./data/Icons/Item Icons/axe.webp'),
  'barbedCarver.webp': require('./data/Icons/Item Icons/barbedCarver.webp'),
  'baseBookOfThoth.webp': require('./data/Icons/Item Icons/baseBookOfThoth.webp'),
  'baseDevourersGauntlet.webp': require('./data/Icons/Item Icons/baseDevourersGauntlet.webp'),
  'basePropheticCloak.webp': require('./data/Icons/Item Icons/basePropheticCloak.webp'),
  'baseTranscendence.webp': require('./data/Icons/Item Icons/baseTranscendence.webp'),
  'bloodSoaked.webp': require('./data/Icons/Item Icons/bloodSoaked.webp'),
  'chandrasDisgrace.webp': require('./data/Icons/Item Icons/chandrasDisgrace.webp'),
  'contagion.webp': require('./data/Icons/Item Icons/contagion.webp'),
  'daybreakGavel.webp': require('./data/Icons/Item Icons/daybreakGavel.webp'),
  'draconicScale.webp': require('./data/Icons/Item Icons/draconicScale.webp'),
  'dwarvenPlate.webp': require('./data/Icons/Item Icons/dwarvenPlate.webp'),
  'erosBow.webp': require('./data/Icons/Item Icons/erosBow.webp'),
  'erosion.webp': require('./data/Icons/Item Icons/erosion.webp'),
  'evolvedRage.webp': require('./data/Icons/Item Icons/evolvedRage.webp'),
  'evolvedThebes.webp': require('./data/Icons/Item Icons/evolvedThebes.webp'),
  'evolvedTrans.webp': require('./data/Icons/Item Icons/evolvedTrans.webp'),
  'eyeOfErebus.webp': require('./data/Icons/Item Icons/eyeOfErebus.webp'),
  'freyasTears.webp': require('./data/Icons/Item Icons/freyasTears.webp'),
  'gildedArrow.webp': require('./data/Icons/Item Icons/gildedArrow.webp'),
  'glutGrimoire.webp': require('./data/Icons/Item Icons/glutGrimoire.webp'),
  'healthChalice.webp': require('./data/Icons/Item Icons/healthChalice.webp'),
  'healthPotion.webp': require('./data/Icons/Item Icons/healthPotion.webp'),
  'CaptainsRing.webp': require('./data/Icons/Item Icons/CaptainsRing.webp'),
 'LegionnaireArmor.webp': require('./data/Icons/Item Icons/LegionnaireArmor.webp'),
  'SoulReliquary.webp': require('./data/Icons/Item Icons/SoulReliquary.webp'),
  'ManaTome.webp': require('./data/Icons/Item Icons/ManaTome.webp'),
  'AdroitRing.webp': require('./data/Icons/Item Icons/AdroitRing.webp'),
  'heartWoodCharm.webp': require('./data/Icons/Item Icons/heartWoodCharm.webp'),
  'nimbleRing.webp': require('./data/Icons/Item Icons/nimbleRing.webp'),
  'regrowthStriders.webp': require('./data/Icons/Item Icons/regrowthStriders.webp'),
  'FlamingPearl.webp': require('./data/Icons/Item Icons/FlamingPearl.webp'),
  'rodOfAsclepius.webp': require('./data/Icons/Item Icons/rodOfAsclepius.webp'),
  'runeForged.webp': require('./data/Icons/Item Icons/runeForged.webp'),
  'sanguineLash.webp': require('./data/Icons/Item Icons/sanguineLash.webp'),
  'LucerneHammer.webp': require('./data/Icons/Item Icons/LucerneHammer.webp'),
  'SagesRing.webp': require('./data/Icons/Item Icons/SagesRing.webp'),
  'shieldsplitter.webp': require('./data/Icons/Item Icons/shieldsplitter.webp'),
  'MedalOfDefense.webp': require('./data/Icons/Item Icons/MedalOfDefense.webp'),
  'Zither.webp': require('./data/Icons/Item Icons/Zither.webp'),
  'EvilEye.webp': require('./data/Icons/Item Icons/EvilEye.webp'),
  'shogunsofuda.webp': require('./data/Icons/Item Icons/shogunsofuda.webp'),
  'MedalOfDisruption.webp': require('./data/Icons/Item Icons/MedalOfDisruption.webp'),
  'silkenmailcoat.webp': require('./data/Icons/Item Icons/silkenmailcoat.webp'),
  'EngravedGuard.webp': require('./data/Icons/Item Icons/EngravedGuard.webp'),
  'staffofmyrddin.webp': require('./data/Icons/Item Icons/staffofmyrddin.webp'),
  'stampede.webp': require('./data/Icons/Item Icons/stampede.webp'),
  'stygianAnchor.webp': require('./data/Icons/Item Icons/stygianAnchor.webp'),
  'sunBeamBow.webp': require('./data/Icons/Item Icons/sunBeamBow.webp'),
  'HuntersBow.webp': require('./data/Icons/Item Icons/HuntersBow.webp'),
  'KillingStone.webp': require('./data/Icons/Item Icons/KillingStone.webp'),
  'sunderingarc.webp': require('./data/Icons/Item Icons/sunderingarc.webp'),
  'sunderingaxe.webp': require('./data/Icons/Item Icons/sunderingaxe.webp'),
  'BattleAxe.webp': require('./data/Icons/Item Icons/BattleAxe.webp'),
  'Skeggox.webp': require('./data/Icons/Item Icons/Skeggox.webp'),
  'CursedSickle.webp': require('./data/Icons/Item Icons/CursedSickle.webp'),
  'EnchantedBracelet.webp': require('./data/Icons/Item Icons/EnchantedBracelet.webp'),
  'VeveCharm.webp': require('./data/Icons/Item Icons/VeveCharm.webp'),
  'SunderingAxeUpgrade.webp': require('./data/Icons/Item Icons/SunderingAxeUpgrade.webp'),
  'typhonsHeart.webp': require('./data/Icons/Item Icons/typhonsHeart.webp'),
  'umbralLink.webp': require('./data/Icons/Item Icons/umbralLink.webp'),
  'vampiricShroud.webp': require('./data/Icons/Item Icons/vampiricShroud.webp'),
  'vitalAmplifier.webp': require('./data/Icons/Item Icons/vitalAmplifier.webp'),
};

// Case-insensitive lookup helper so JSON/icon paths can use any casing.
const itemIconMapLower = {};
for (const key of Object.keys(itemIconMap)) {
  itemIconMapLower[key.toLowerCase()] = itemIconMap[key];
}

export function getLocalItemIcon(iconPath) {
  if (!iconPath) return null;
  const base = iconPath.split('/').pop() || '';
  // Try exact match first, then case-insensitive match.
  return itemIconMap[base] || itemIconMapLower[base.toLowerCase()] || null;
}

// God / ability / aspect / passive / skin icons from `app/data/Icons/God Info/jacob_s icons`
// NOTE: React Native requires static require() paths, so you must add entries here manually
// keyed by the exact JSON icon path (e.g. '/icons/vulcanImage.webp').
// Example (uncomment and edit to use):
// const godAssetMap = {
//   '/icons/vulcanImage.webp': require('./data/Icons/God Info/jacob_s icons/vulcanImage.webp'),
//   '/icons/vulcanOne.webp': require('./data/Icons/God Info/jacob_s icons/vulcanOne.webp'),
//   '/icons/vulcanTwo.webp': require('./data/Icons/God Info/jacob_s icons/vulcanTwo.webp'),
//   '/icons/vulcanThree.webp': require('./data/Icons/God Info/jacob_s icons/vulcanThree.webp'),
//   '/icons/vulcanFour.webp': require('./data/Icons/God Info/jacob_s icons/vulcanFour.webp'),
//   '/icons/vulcanAspect.webp': require('./data/Icons/God Info/jacob_s icons/vulcanAspect.webp'),
//   '/icons/vulcanPassive.webp': require('./data/Icons/God Info/jacob_s icons/vulcanPassive.webp'),
// };
// God / ability / aspect / passive / skin icons from `app/data/Icons/God Info/jacob_s icons`
// Keys are basenames (e.g. "vulcanImage.webp"); lookup is case-insensitive.
const godAssetMap = {
  'achillesImage.webp': require('./data/Icons/God Info/jacob_s icons/achillesImage.webp'),
  'achillesOne.webp': require('./data/Icons/God Info/jacob_s icons/achillesOne.webp'),
  'achillesTwo.webp': require('./data/Icons/God Info/jacob_s icons/achillesTwo.webp'),
  'achillesThree.webp': require('./data/Icons/God Info/jacob_s icons/achillesThree.webp'),
  'achillesFour.webp': require('./data/Icons/God Info/jacob_s icons/achillesFour.webp'),
  'achillesPassive.webp': require('./data/Icons/God Info/jacob_s icons/achillesPassive.webp'),
  'achillesAspect.webp': require('./data/Icons/God Info/jacob_s icons/achillesAspect.webp'),
  'agniImage.webp': require('./data/Icons/God Info/jacob_s icons/agniImage.webp'),
  'agniOne.webp': require('./data/Icons/God Info/jacob_s icons/agniOne.webp'),
  'agniTwo.webp': require('./data/Icons/God Info/jacob_s icons/agniTwo.webp'),
  'agniThree.webp': require('./data/Icons/God Info/jacob_s icons/agniThree.webp'),
  'agniFour.webp': require('./data/Icons/God Info/jacob_s icons/agniFour.webp'),
  'agniPassive.webp': require('./data/Icons/God Info/jacob_s icons/agniPassive.webp'),
  'agniAspect.webp': require('./data/Icons/God Info/jacob_s icons/agniAspect.webp'),
  'aladdinImage.webp': require('./data/Icons/God Info/jacob_s icons/aladdinImage.webp'),
  'aladdinOne.webp': require('./data/Icons/God Info/jacob_s icons/aladdinOne.webp'),
  'aladdinTwo.webp': require('./data/Icons/God Info/jacob_s icons/aladdinTwo.webp'),
  'aladdinThree.webp': require('./data/Icons/God Info/jacob_s icons/aladdinThree.webp'),
  'aladdinFour.webp': require('./data/Icons/God Info/jacob_s icons/aladdinFour.webp'),
  'aladdinPassive.webp': require('./data/Icons/God Info/jacob_s icons/aladdinPassive.webp'),
  'amaImage.webp': require('./data/Icons/God Info/jacob_s icons/amaImage.webp'),
  'amaOne.webp': require('./data/Icons/God Info/jacob_s icons/amaOne.webp'),
  'amaTwo.webp': require('./data/Icons/God Info/jacob_s icons/amaTwo.webp'),
  'amaThree.webp': require('./data/Icons/God Info/jacob_s icons/amaThree.webp'),
  'amaFour.webp': require('./data/Icons/God Info/jacob_s icons/amaFour.webp'),
  'amaPassive.webp': require('./data/Icons/God Info/jacob_s icons/amaPassive.webp'),
  'amaAspect.webp': require('./data/Icons/God Info/jacob_s icons/amaAspect.webp'),
  'anhurImage.webp': require('./data/Icons/God Info/jacob_s icons/anhurImage.webp'),
  'anhurOne.webp': require('./data/Icons/God Info/jacob_s icons/anhurOne.webp'),
  'anhurTwo.webp': require('./data/Icons/God Info/jacob_s icons/anhurTwo.webp'),
  'anhurThree.webp': require('./data/Icons/God Info/jacob_s icons/anhurThree.webp'),
  'anhurFour.webp': require('./data/Icons/God Info/jacob_s icons/anhurFour.webp'),
  'anhurPassive.webp': require('./data/Icons/God Info/jacob_s icons/anhurPassive.webp'),
  'anhurAspect.webp': require('./data/Icons/God Info/jacob_s icons/anhurAspect.webp'),
  'anubisImage.webp': require('./data/Icons/God Info/jacob_s icons/anubisImage.webp'),
  'anubisOne.webp': require('./data/Icons/God Info/jacob_s icons/anubisOne.webp'),
  'anubisTwo.webp': require('./data/Icons/God Info/jacob_s icons/anubisTwo.webp'),
  'anubisThree.webp': require('./data/Icons/God Info/jacob_s icons/anubisThree.webp'),
  'anubisFour.webp': require('./data/Icons/God Info/jacob_s icons/anubisFour.webp'),
  'anubisPassive.webp': require('./data/Icons/God Info/jacob_s icons/anubisPassive.webp'),
  'aphroImage.webp': require('./data/Icons/God Info/jacob_s icons/aphroImage.webp'),
  'aphroOne.webp': require('./data/Icons/God Info/jacob_s icons/aphroOne.webp'),
  'aphroTwo.webp': require('./data/Icons/God Info/jacob_s icons/aphroTwo.webp'),
  'aphroThree.webp': require('./data/Icons/God Info/jacob_s icons/aphroThree.webp'),
  'aphroFour.webp': require('./data/Icons/God Info/jacob_s icons/aphroFour.webp'),
  'aphroPassive.webp': require('./data/Icons/God Info/jacob_s icons/aphroPassive.webp'),
  'apolloImage.webp': require('./data/Icons/God Info/jacob_s icons/apolloImage.webp'),
  'apolloOne.webp': require('./data/Icons/God Info/jacob_s icons/apolloOne.webp'),
  'apolloTwo.webp': require('./data/Icons/God Info/jacob_s icons/apolloTwo.webp'),
  'apolloThree.webp': require('./data/Icons/God Info/jacob_s icons/apolloThree.webp'),
  'apolloFour.webp': require('./data/Icons/God Info/jacob_s icons/apolloFour.webp'),
  'apolloPassive.webp': require('./data/Icons/God Info/jacob_s icons/apolloPassive.webp'),
  'apolloAspect.webp': require('./data/Icons/God Info/jacob_s icons/apolloAspect.webp'),
  'aresImage.webp': require('./data/Icons/God Info/jacob_s icons/aresImage.webp'),
  'aresOne.webp': require('./data/Icons/God Info/jacob_s icons/aresOne.webp'),
  'aresTwo.webp': require('./data/Icons/God Info/jacob_s icons/aresTwo.webp'),
  'aresThree.webp': require('./data/Icons/God Info/jacob_s icons/aresThree.webp'),
  'aresFour.webp': require('./data/Icons/God Info/jacob_s icons/aresFour.webp'),
  'aresPassive.webp': require('./data/Icons/God Info/jacob_s icons/aresPassive.webp'),
  'aresAspect.webp': require('./data/Icons/God Info/jacob_s icons/aresAspect.webp'),
  'artemisImage.webp': require('./data/Icons/God Info/jacob_s icons/artemisImage.webp'),
  'artemisOne.webp': require('./data/Icons/God Info/jacob_s icons/artemisOne.webp'),
  'artemisTwo.webp': require('./data/Icons/God Info/jacob_s icons/artemisTwo.webp'),
  'artemisThree.webp': require('./data/Icons/God Info/jacob_s icons/artemisThree.webp'),
  'artemisFour.webp': require('./data/Icons/God Info/jacob_s icons/artemisFour.webp'),
  'artemisPassive.webp': require('./data/Icons/God Info/jacob_s icons/artemisPassive.webp'),
  'artemisAspect.webp': require('./data/Icons/God Info/jacob_s icons/artemisAspect.webp'),
  'athenaImage.webp': require('./data/Icons/God Info/jacob_s icons/athenaImage.webp'),
  'athenaOne.webp': require('./data/Icons/God Info/jacob_s icons/athenaOne.webp'),
  'athenaTwo.webp': require('./data/Icons/God Info/jacob_s icons/athenaTwo.webp'),
  'athenaThree.webp': require('./data/Icons/God Info/jacob_s icons/athenaThree.webp'),
  'athenaFour.webp': require('./data/Icons/God Info/jacob_s icons/athenaFour.webp'),
  'athenaPassive.webp': require('./data/Icons/God Info/jacob_s icons/athenaPassive.webp'),
  'athenaAspect.webp': require('./data/Icons/God Info/jacob_s icons/athenaAspect.webp'),
  'awilixImage.webp': require('./data/Icons/God Info/jacob_s icons/awilixImage.webp'),
  'awilixOne.webp': require('./data/Icons/God Info/jacob_s icons/awilixOne.webp'),
  'awilixTwo.webp': require('./data/Icons/God Info/jacob_s icons/awilixTwo.webp'),
  'awilixThree.webp': require('./data/Icons/God Info/jacob_s icons/awilixThree.webp'),
  'awilixFour.webp': require('./data/Icons/God Info/jacob_s icons/awilixFour.webp'),
  'awilixPassive.webp': require('./data/Icons/God Info/jacob_s icons/awilixPassive.webp'),
  'bacchusImage.webp': require('./data/Icons/God Info/jacob_s icons/bacchusImage.webp'),
  'bacchusOne.webp': require('./data/Icons/God Info/jacob_s icons/bacchusOne.webp'),
  'bacchusTwo.webp': require('./data/Icons/God Info/jacob_s icons/bacchusTwo.webp'),
  'bacchusThree.webp': require('./data/Icons/God Info/jacob_s icons/bacchusThree.webp'),
  'bacchusFour.webp': require('./data/Icons/God Info/jacob_s icons/bacchusFour.webp'),
  'bacchusPassive.webp': require('./data/Icons/God Info/jacob_s icons/bacchusPassive.webp'),
  'bacchusAspect.webp': require('./data/Icons/God Info/jacob_s icons/bacchusAspect.webp'),
  'bariImage.webp': require('./data/Icons/God Info/jacob_s icons/bariImage.webp'),
  'bariOne.webp': require('./data/Icons/God Info/jacob_s icons/bariOne.webp'),
  'bariTwo.webp': require('./data/Icons/God Info/jacob_s icons/bariTwo.webp'),
  'bariThree.webp': require('./data/Icons/God Info/jacob_s icons/bariThree.webp'),
  'bariFour.webp': require('./data/Icons/God Info/jacob_s icons/bariFour.webp'),
  'bariPassive.webp': require('./data/Icons/God Info/jacob_s icons/bariPassive.webp'),
  'baronImage.webp': require('./data/Icons/God Info/jacob_s icons/baronImage.webp'),
  'baronOne.webp': require('./data/Icons/God Info/jacob_s icons/baronOne.webp'),
  'baronTwo.webp': require('./data/Icons/God Info/jacob_s icons/baronTwo.webp'),
  'baronThree.webp': require('./data/Icons/God Info/jacob_s icons/baronThree.webp'),
  'baronFour.webp': require('./data/Icons/God Info/jacob_s icons/baronFour.webp'),
  'baronPassive.webp': require('./data/Icons/God Info/jacob_s icons/baronPassive.webp'),
  'baronAspect.webp': require('./data/Icons/God Info/jacob_s icons/baronAspect.webp'),
  'batzImage.webp': require('./data/Icons/God Info/jacob_s icons/batzImage.webp'),
  'batzOne.webp': require('./data/Icons/God Info/jacob_s icons/batzOne.webp'),
  'batzTwo.webp': require('./data/Icons/God Info/jacob_s icons/batzTwo.webp'),
  'batzThree.webp': require('./data/Icons/God Info/jacob_s icons/batzThree.webp'),
  'batzFour.webp': require('./data/Icons/God Info/jacob_s icons/batzFour.webp'),
  'batzPassive.webp': require('./data/Icons/God Info/jacob_s icons/batzPassive.webp'),
  'batzAspect.webp': require('./data/Icons/God Info/jacob_s icons/batzAspect.webp'),
  'belloImage.webp': require('./data/Icons/God Info/jacob_s icons/belloImage.webp'),
  'bellOne.webp': require('./data/Icons/God Info/jacob_s icons/bellOne.webp'),
  'bellTwo.webp': require('./data/Icons/God Info/jacob_s icons/bellTwo.webp'),
  'bellThree.webp': require('./data/Icons/God Info/jacob_s icons/bellThree.webp'),
  'bellFour.webp': require('./data/Icons/God Info/jacob_s icons/bellFour.webp'),
  'bellPassive.webp': require('./data/Icons/God Info/jacob_s icons/bellPassive.webp'),
  'bellAspect.webp': require('./data/Icons/God Info/jacob_s icons/bellAspect.webp'),
  // Bellona - JSON uses bellonaImage.webp but file is belloImage.webp
  'bellonaImage.webp': require('./data/Icons/God Info/jacob_s icons/belloImage.webp'),
  'bellonaOne.webp': require('./data/Icons/God Info/jacob_s icons/bellOne.webp'),
  'bellonaTwo.webp': require('./data/Icons/God Info/jacob_s icons/bellTwo.webp'),
  'bellonaThree.webp': require('./data/Icons/God Info/jacob_s icons/bellThree.webp'),
  'bellonaFour.webp': require('./data/Icons/God Info/jacob_s icons/bellFour.webp'),
  'bellonaPassive.webp': require('./data/Icons/God Info/jacob_s icons/bellPassive.webp'),
  'bellonaAspect.webp': require('./data/Icons/God Info/jacob_s icons/bellAspect.webp'),
  'cabImage.webp': require('./data/Icons/God Info/jacob_s icons/cabImage.webp'),
  'cabOne.webp': require('./data/Icons/God Info/jacob_s icons/cabOne.webp'),
  'cabTwo.webp': require('./data/Icons/God Info/jacob_s icons/cabTwo.webp'),
  'cabThree.webp': require('./data/Icons/God Info/jacob_s icons/cabThree.webp'),
  'cabFour.webp': require('./data/Icons/God Info/jacob_s icons/cabFour.webp'),
  'cabPassive.webp': require('./data/Icons/God Info/jacob_s icons/cabPassive.webp'),
  'cabAspect.webp': require('./data/Icons/God Info/jacob_s icons/cabAspect.webp'),
  'cerbImage.webp': require('./data/Icons/God Info/jacob_s icons/cerbImage.webp'),
  'cerbOne.webp': require('./data/Icons/God Info/jacob_s icons/cerbOne.webp'),
  'cerbTwo.webp': require('./data/Icons/God Info/jacob_s icons/cerbTwo.webp'),
  'cerbThree.webp': require('./data/Icons/God Info/jacob_s icons/cerbThree.webp'),
  'cerbFour.webp': require('./data/Icons/God Info/jacob_s icons/cerbFour.webp'),
  'cerbPassive.webp': require('./data/Icons/God Info/jacob_s icons/cerbPassive.webp'),
  'cernImage.webp': require('./data/Icons/God Info/jacob_s icons/cernImage.webp'),
  'cernOne.webp': require('./data/Icons/God Info/jacob_s icons/cernOne.webp'),
  'cernTwo.webp': require('./data/Icons/God Info/jacob_s icons/cernTwo.webp'),
  'cernThree.webp': require('./data/Icons/God Info/jacob_s icons/cernThree.webp'),
  'cernFour.webp': require('./data/Icons/God Info/jacob_s icons/cernFour.webp'),
  'cernPassive.webp': require('./data/Icons/God Info/jacob_s icons/cernPassive.webp'),
  'cernAspect.webp': require('./data/Icons/God Info/jacob_s icons/cernAspect.webp'),
  // Cernunnos - JSON uses cernunnosImage.webp but files are cern*.webp
  'cernunnosImage.webp': require('./data/Icons/God Info/jacob_s icons/cernImage.webp'),
  'cernunnosOne.webp': require('./data/Icons/God Info/jacob_s icons/cernOne.webp'),
  'cernunnosTwo.webp': require('./data/Icons/God Info/jacob_s icons/cernTwo.webp'),
  'cernunnosThree.webp': require('./data/Icons/God Info/jacob_s icons/cernThree.webp'),
  'cernunnosFour.webp': require('./data/Icons/God Info/jacob_s icons/cernFour.webp'),
  'cernunnosPassive.webp': require('./data/Icons/God Info/jacob_s icons/cernPassive.webp'),
  'cernunnosAspect.webp': require('./data/Icons/God Info/jacob_s icons/cernAspect.webp'),
  'chaacImage.webp': require('./data/Icons/God Info/jacob_s icons/chaacImage.webp'),
  'chaacOne.webp': require('./data/Icons/God Info/jacob_s icons/chaacOne.webp'),
  'chaacTwo.webp': require('./data/Icons/God Info/jacob_s icons/chaacTwo.webp'),
  'chaacThree.webp': require('./data/Icons/God Info/jacob_s icons/chaacThree.webp'),
  'chaacFour.webp': require('./data/Icons/God Info/jacob_s icons/chaacFour.webp'),
  'chaacPassive.webp': require('./data/Icons/God Info/jacob_s icons/chaacPassive.webp'),
  'chaacAspect.webp': require('./data/Icons/God Info/jacob_s icons/chaacAspect.webp'),
  'cupidImage.webp': require('./data/Icons/God Info/jacob_s icons/cupidImage.webp'),
  'cupidOne.webp': require('./data/Icons/God Info/jacob_s icons/cupidOne.webp'),
  'cupidTwo.webp': require('./data/Icons/God Info/jacob_s icons/cupidTwo.webp'),
  'cupidThree.webp': require('./data/Icons/God Info/jacob_s icons/cupidThree.webp'),
  'cupidFour.webp': require('./data/Icons/God Info/jacob_s icons/cupidFour.webp'),
  'cupidPassive.webp': require('./data/Icons/God Info/jacob_s icons/cupidPassive.webp'),
  'cupidAspect.webp': require('./data/Icons/God Info/jacob_s icons/cupidAspect.webp'),
  'daJiImage.webp': require('./data/Icons/God Info/jacob_s icons/daJiImage.webp'),
  'daJiOne.webp': require('./data/Icons/God Info/jacob_s icons/daJiOne.webp'),
  'daJiTwo.webp': require('./data/Icons/God Info/jacob_s icons/daJiTwo.webp'),
  'daJiThree.webp': require('./data/Icons/God Info/jacob_s icons/daJiThree.webp'),
  'daJiFour.webp': require('./data/Icons/God Info/jacob_s icons/daJiFour.webp'),
  'daJiPassive.webp': require('./data/Icons/God Info/jacob_s icons/daJiPassive.webp'),
  'daJiAspect.webp': require('./data/Icons/God Info/jacob_s icons/dajiAspect.webp'),
  'danzaImage.webp': require('./data/Icons/God Info/jacob_s icons/danzaImage.webp'),
  'danzaTwo.webp': require('./data/Icons/God Info/jacob_s icons/danzaTwo.webp'),
  'danzaThree.webp': require('./data/Icons/God Info/jacob_s icons/danzaThree.webp'),
  'danzaFour.webp': require('./data/Icons/God Info/jacob_s icons/danzaFour.webp'),
  'danzaPassive.webp': require('./data/Icons/God Info/jacob_s icons/danzaPassive.webp'),
  'danzaAspect.webp': require('./data/Icons/God Info/jacob_s icons/danzaAspect.webp'),
  'danzOne.webp': require('./data/Icons/God Info/jacob_s icons/danzeOne.webp'),
  'esetImage.webp': require('./data/Icons/God Info/jacob_s icons/esetImage.webp'),
  'esetOne.webp': require('./data/Icons/God Info/jacob_s icons/esetOne.webp'),
  'esetTwo.webp': require('./data/Icons/God Info/jacob_s icons/esetTwo.webp'),
  'esetThree.webp': require('./data/Icons/God Info/jacob_s icons/esetThree.webp'),
  'esetFour.webp': require('./data/Icons/God Info/jacob_s icons/esetFour.webp'),
  'esetPassive.webp': require('./data/Icons/God Info/jacob_s icons/esetPassive.webp'),
  'esetAspect.webp': require('./data/Icons/God Info/jacob_s icons/EsetAspect .webp'),
  'fenrirImage.webp': require('./data/Icons/God Info/jacob_s icons/fenrirImage.webp'),
  'fenrirOne.webp': require('./data/Icons/God Info/jacob_s icons/fenrirOne.webp'),
  'fenrirTwo.webp': require('./data/Icons/God Info/jacob_s icons/fenrirTwo.webp'),
  'fenrirThree.webp': require('./data/Icons/God Info/jacob_s icons/fenrirThree.webp'),
  'fenrirFour.webp': require('./data/Icons/God Info/jacob_s icons/fenrirFour.webp'),
  'fenrirPassive.webp': require('./data/Icons/God Info/jacob_s icons/fenrirPassive.webp'),
  'fenrirAspect.webp': require('./data/Icons/God Info/jacob_s icons/fenrirAspect.webp'),
  'ganeshaAspect.webp': require('./data/Icons/God Info/jacob_s icons/ganashaAspect .webp'),
  'ganeshaImage.webp': require('./data/Icons/God Info/jacob_s icons/ganeshaImage.webp'),
  'ganeshaOne.webp': require('./data/Icons/God Info/jacob_s icons/ganeshaOne.webp'),
  'ganeshaTwo.webp': require('./data/Icons/God Info/jacob_s icons/ganeshaTwo.webp'),
  'ganeshaThree.webp': require('./data/Icons/God Info/jacob_s icons/ganeshaThree.webp'),
  'ganeshaFour.webp': require('./data/Icons/God Info/jacob_s icons/ganeshaFour.webp'),
  'ganeshaPassive.webp': require('./data/Icons/God Info/jacob_s icons/ganeshaPassive.webp'),
  'gebImage.webp': require('./data/Icons/God Info/jacob_s icons/gebImage.webp'),
  'gebOne.webp': require('./data/Icons/God Info/jacob_s icons/gebOne.webp'),
  'gebTwo.webp': require('./data/Icons/God Info/jacob_s icons/gebTwo.webp'),
  'gebThree.webp': require('./data/Icons/God Info/jacob_s icons/gebThree.webp'),
  'gebFour.webp': require('./data/Icons/God Info/jacob_s icons/gebFour.webp'),
  'gebPassive.webp': require('./data/Icons/God Info/jacob_s icons/gebPassive.webp'),
  'gebAspect.webp': require('./data/Icons/God Info/jacob_s icons/gebAspect.webp'),
  'guanImage.webp': require('./data/Icons/God Info/jacob_s icons/guanImage.webp'),
  'guanOne.webp': require('./data/Icons/God Info/jacob_s icons/guanOne.webp'),
  'guanTwo.webp': require('./data/Icons/God Info/jacob_s icons/guanTwo.webp'),
  'guanThree.webp': require('./data/Icons/God Info/jacob_s icons/guanThree.webp'),
  'guanFour.webp': require('./data/Icons/God Info/jacob_s icons/guanFour.webp'),
  'guanPassive.webp': require('./data/Icons/God Info/jacob_s icons/guanPassive.webp'),
  'hadesImage.webp': require('./data/Icons/God Info/jacob_s icons/hadesImage.webp'),
  'hadesOne.webp': require('./data/Icons/God Info/jacob_s icons/hadesOne.webp'),
  'hadesTwo.webp': require('./data/Icons/God Info/jacob_s icons/hadesTWO.webp'),
  'hadesThree.webp': require('./data/Icons/God Info/jacob_s icons/hadesThree.webp'),
  'hadesFour.webp': require('./data/Icons/God Info/jacob_s icons/hadesFour.webp'),
  'hadesPassive.webp': require('./data/Icons/God Info/jacob_s icons/hadesPassive.webp'),
  'hecateImage.webp': require('./data/Icons/God Info/jacob_s icons/hecateImage.webp'),
  'hecateOne.webp': require('./data/Icons/God Info/jacob_s icons/hecateOne.webp'),
  'hecateTwo.webp': require('./data/Icons/God Info/jacob_s icons/hecateTwo.webp'),
  'hecateThree.webp': require('./data/Icons/God Info/jacob_s icons/hecateThree.webp'),
  'hecateFour.webp': require('./data/Icons/God Info/jacob_s icons/hecateFour.webp'),
  'hecatePassive.webp': require('./data/Icons/God Info/jacob_s icons/hecatePassive.webp'),
  'hecateAspect.webp': require('./data/Icons/God Info/jacob_s icons/hecateAspect.webp'),
  'hercImage.webp': require('./data/Icons/God Info/jacob_s icons/hercImage.webp'),
  'hercOne.webp': require('./data/Icons/God Info/jacob_s icons/hercOne.webp'),
  'hercTwo.webp': require('./data/Icons/God Info/jacob_s icons/hercTwo.webp'),
  'hercThree.webp': require('./data/Icons/God Info/jacob_s icons/hercThree.webp'),
  'hercFour.webp': require('./data/Icons/God Info/jacob_s icons/hercFour.webp'),
  'hercPassive.webp': require('./data/Icons/God Info/jacob_s icons/hercPassive.webp'),
  'hercAspect.webp': require('./data/Icons/God Info/jacob_s icons/hercAspect.webp'),
  'houYiAspect.webp': require('./data/Icons/God Info/jacob_s icons/HouYiAspect.webp'),
  'houYiImage.webp': require('./data/Icons/God Info/jacob_s icons/houYiImage.webp'),
  'houYiOne.webp': require('./data/Icons/God Info/jacob_s icons/houYiOne.webp'),
  'houYiTwo.webp': require('./data/Icons/God Info/jacob_s icons/houYiTwo.webp'),
  'houYiThree.webp': require('./data/Icons/God Info/jacob_s icons/houYiThree.webp'),
  'houYiFour.webp': require('./data/Icons/God Info/jacob_s icons/houYiFour.webp'),
  'houYiPassive.webp': require('./data/Icons/God Info/jacob_s icons/houYiPassive.webp'),
  'izaImage.webp': require('./data/Icons/God Info/jacob_s icons/izaImage.webp'),
  'izaOne.webp': require('./data/Icons/God Info/jacob_s icons/izaOne.webp'),
  'izaTwo.webp': require('./data/Icons/God Info/jacob_s icons/izaTwo.webp'),
  'izaThree.webp': require('./data/Icons/God Info/jacob_s icons/izaThree.webp'),
  'izaFour.webp': require('./data/Icons/God Info/jacob_s icons/izaFour.webp'),
  'izaPassive.webp': require('./data/Icons/God Info/jacob_s icons/izaPassive.webp'),
  'JanusImage.webp': require('./data/Icons/God Info/jacob_s icons/janusImage.webp'),
  'jingImage.webp': require('./data/Icons/God Info/jacob_s icons/jingImage.webp'),
  'jingOne.webp': require('./data/Icons/God Info/jacob_s icons/jingOne.webp'),
  'jingTwo.webp': require('./data/Icons/God Info/jacob_s icons/jingTwo.webp'),
  'jingThree.webp': require('./data/Icons/God Info/jacob_s icons/jingThree.webp'),
  'jingFour.webp': require('./data/Icons/God Info/jacob_s icons/jingFour.webp'),
  'jingPassive.webp': require('./data/Icons/God Info/jacob_s icons/jingPassive.webp'),
  'jormImage.webp': require('./data/Icons/God Info/jacob_s icons/jormImage.webp'),
  'jormOne.webp': require('./data/Icons/God Info/jacob_s icons/jormOne.webp'),
  'jormTwo.webp': require('./data/Icons/God Info/jacob_s icons/jormTwo.webp'),
  'jormThree.webp': require('./data/Icons/God Info/jacob_s icons/jormThree.webp'),
  'jormFour.webp': require('./data/Icons/God Info/jacob_s icons/jormUlt.webp'),
  'jormPassive.webp': require('./data/Icons/God Info/jacob_s icons/jormPassive.webp'),
  'jormAspect.webp': require('./data/Icons/God Info/jacob_s icons/JormAspect.webp'),
  'kaliImage.webp': require('./data/Icons/God Info/jacob_s icons/kaliImage.webp'),
  'kaliOne.webp': require('./data/Icons/God Info/jacob_s icons/kaliOne.webp'),
  'kaliTwo.webp': require('./data/Icons/God Info/jacob_s icons/kaliTwo.webp'),
  'kaliThree.webp': require('./data/Icons/God Info/jacob_s icons/kaliThree.webp'),
  'kaliFour.webp': require('./data/Icons/God Info/jacob_s icons/kaliFour.webp'),
  'kaliPassive.webp': require('./data/Icons/God Info/jacob_s icons/kaliPassive.webp'),
  'kaliAspect.webp': require('./data/Icons/God Info/jacob_s icons/kaliAspect.webp'),
  'khepImage.webp': require('./data/Icons/God Info/jacob_s icons/khepImage.webp'),
  'khepOne.webp': require('./data/Icons/God Info/jacob_s icons/khepOne.webp'),
  'khepTwo.webp': require('./data/Icons/God Info/jacob_s icons/khepTwo.webp'),
  'khepThree.webp': require('./data/Icons/God Info/jacob_s icons/khepThree.webp'),
  'khepFour.webp': require('./data/Icons/God Info/jacob_s icons/khepFour.webp'),
  'khepPassive.webp': require('./data/Icons/God Info/jacob_s icons/khepPassive.webp'),
  'khepAspect.webp': require('./data/Icons/God Info/jacob_s icons/khepAspect.webp'),
  'kukuImage.webp': require('./data/Icons/God Info/jacob_s icons/kukuImage.webp'),
  'kukuOne.webp': require('./data/Icons/God Info/jacob_s icons/kukuOne.webp'),
  'kukuTwo.webp': require('./data/Icons/God Info/jacob_s icons/kukuTwo.webp'),
  'kukuThree.webp': require('./data/Icons/God Info/jacob_s icons/kukuThree.webp'),
  'kukuFour.webp': require('./data/Icons/God Info/jacob_s icons/kukuFour.webp'),
  'kukuPassive.webp': require('./data/Icons/God Info/jacob_s icons/kukuPassive.webp'),
  'lokiImage.webp': require('./data/Icons/God Info/jacob_s icons/lokiImage.webp'),
  'lokiOne.webp': require('./data/Icons/God Info/jacob_s icons/lokiOne.webp'),
  'lokiTwo.webp': require('./data/Icons/God Info/jacob_s icons/lokiTwo.webp'),
  'lokiThree.webp': require('./data/Icons/God Info/jacob_s icons/lokiThree.webp'),
  'lokiFour.webp': require('./data/Icons/God Info/jacob_s icons/lokiFour.webp'),
  'lokiPassive.webp': require('./data/Icons/God Info/jacob_s icons/lokiPassive.webp'),
  'lokiAspect.webp': require('./data/Icons/God Info/jacob_s icons/lokiAspect.webp'),
  'medusaImage.webp': require('./data/Icons/God Info/jacob_s icons/medusaImage.webp'),
  'medusaOne.webp': require('./data/Icons/God Info/jacob_s icons/medusaOne.webp'),
  'medusaTwo.webp': require('./data/Icons/God Info/jacob_s icons/medusaTwo.webp'),
  'medusaThree.webp': require('./data/Icons/God Info/jacob_s icons/medusaThree.webp'),
  'medusaFour.webp': require('./data/Icons/God Info/jacob_s icons/medusaFour.webp'),
  'medusaPassive.webp': require('./data/Icons/God Info/jacob_s icons/medusaPassive.webp'),
  'mercImage.webp': require('./data/Icons/God Info/jacob_s icons/mercImage.webp'),
  'mercOne.webp': require('./data/Icons/God Info/jacob_s icons/mercOne.webp'),
  'mercTwo.webp': require('./data/Icons/God Info/jacob_s icons/mercTwo.webp'),
  'mercThree.webp': require('./data/Icons/God Info/jacob_s icons/mercThree.webp'),
  'mercFour.webp': require('./data/Icons/God Info/jacob_s icons/mercFour.webp'),
  'mercPassive.webp': require('./data/Icons/God Info/jacob_s icons/mercPassive.webp'),
  'merlinImage.webp': require('./data/Icons/God Info/jacob_s icons/merlinImage.webp'),
  'merlinPassive.webp': require('./data/Icons/God Info/jacob_s icons/merlinPassive.webp'),
  'merlinAspect.webp': require('./data/Icons/God Info/jacob_s icons/merlinAspect.webp'),
  'mordredImage.webp': require('./data/Icons/God Info/jacob_s icons/mordredImage.webp'),
  'mordredOne.webp': require('./data/Icons/God Info/jacob_s icons/mordredOne.webp'),
  'mordredTwo.webp': require('./data/Icons/God Info/jacob_s icons/mordredTwo.webp'),
  'mordredThree.webp': require('./data/Icons/God Info/jacob_s icons/mordredThree.webp'),
  'mordredFour.webp': require('./data/Icons/God Info/jacob_s icons/mordredFour.webp'),
  'mordredPassive.webp': require('./data/Icons/God Info/jacob_s icons/mordredPassive.webp'),
  'mordredAspect.webp': require('./data/Icons/God Info/jacob_s icons/mordredAspect.webp'),
  'MorriTImage.webp': require('./data/Icons/God Info/jacob_s icons/MorriTImage.webp'),
  'morriOne.webp': require('./data/Icons/God Info/jacob_s icons/morriOne.webp'),
  'morriTwo.webp': require('./data/Icons/God Info/jacob_s icons/morriTwo.webp'),
  'morriThree.webp': require('./data/Icons/God Info/jacob_s icons/morriThree.webp'),
  'morriFour.webp': require('./data/Icons/God Info/jacob_s icons/morriFour.webp'),
  'morriPassive.webp': require('./data/Icons/God Info/jacob_s icons/morriPassive.webp'),
  'morriAspect.webp': require('./data/Icons/God Info/jacob_s icons/morriAspect.webp'),
  // TheMorrigan - JSON uses morriganImage.webp but file is MorriTImage.webp
  'morriganImage.webp': require('./data/Icons/God Info/jacob_s icons/MorriTImage.webp'),
  'morriganOne.webp': require('./data/Icons/God Info/jacob_s icons/morriOne.webp'),
  'morriganTwo.webp': require('./data/Icons/God Info/jacob_s icons/morriTwo.webp'),
  'morriganThree.webp': require('./data/Icons/God Info/jacob_s icons/morriThree.webp'),
  'morriganFour.webp': require('./data/Icons/God Info/jacob_s icons/morriFour.webp'),
  'morriganPassive.webp': require('./data/Icons/God Info/jacob_s icons/morriPassive.webp'),
  'morriganAspect.webp': require('./data/Icons/God Info/jacob_s icons/morriAspect.webp'),
  'theMorriganImage.webp': require('./data/Icons/God Info/jacob_s icons/MorriTImage.webp'),
  'theMorriganOne.webp': require('./data/Icons/God Info/jacob_s icons/morriOne.webp'),
  'theMorriganTwo.webp': require('./data/Icons/God Info/jacob_s icons/morriTwo.webp'),
  'theMorriganThree.webp': require('./data/Icons/God Info/jacob_s icons/morriThree.webp'),
  'theMorriganFour.webp': require('./data/Icons/God Info/jacob_s icons/morriFour.webp'),
  'theMorriganPassive.webp': require('./data/Icons/God Info/jacob_s icons/morriPassive.webp'),
  'theMorriganAspect.webp': require('./data/Icons/God Info/jacob_s icons/morriAspect.webp'),
  'mulanImage.webp': require('./data/Icons/God Info/jacob_s icons/mulanImage.webp'),
  'mulanOne.webp': require('./data/Icons/God Info/jacob_s icons/mulanOne.webp'),
  'mulanTwo.webp': require('./data/Icons/God Info/jacob_s icons/mulanTwo.webp'),
  'mulanThree.webp': require('./data/Icons/God Info/jacob_s icons/mulanThree.webp'),
  'mulanFour.webp': require('./data/Icons/God Info/jacob_s icons/mulanFour.webp'),
  'mulanPassive.webp': require('./data/Icons/God Info/jacob_s icons/mulanPassive.webp'),
  'neithImage.webp': require('./data/Icons/God Info/jacob_s icons/neithImage.webp'),
  'neithOne.webp': require('./data/Icons/God Info/jacob_s icons/neithOne.webp'),
  'neithTwo.webp': require('./data/Icons/God Info/jacob_s icons/neithTwo.webp'),
  'neithThree.webp': require('./data/Icons/God Info/jacob_s icons/neithThree.webp'),
  'neithFour.webp': require('./data/Icons/God Info/jacob_s icons/neithFour.webp'),
  'neithPassive.webp': require('./data/Icons/God Info/jacob_s icons/neithPassive.webp'),
  'neithAspect.webp': require('./data/Icons/God Info/jacob_s icons/neithAspect.webp'),
  'nemImage.webp': require('./data/Icons/God Info/jacob_s icons/nemImage.webp'),
  'nemOne.webp': require('./data/Icons/God Info/jacob_s icons/nemOne.webp'),
  'nemTwo.webp': require('./data/Icons/God Info/jacob_s icons/nemTwo.webp'),
  'nemThree.webp': require('./data/Icons/God Info/jacob_s icons/nemThree.webp'),
  'nemFour.webp': require('./data/Icons/God Info/jacob_s icons/nemFour.webp'),
  'nemPassive.webp': require('./data/Icons/God Info/jacob_s icons/nemPassive.webp'),
  'nemAspect.webp': require('./data/Icons/God Info/jacob_s icons/nemAspect.webp'),
  'nuWaImage.webp': require('./data/Icons/God Info/jacob_s icons/nuWaImage.webp'),
  'nuWaOne.webp': require('./data/Icons/God Info/jacob_s icons/nuWaOne.webp'),
  'nuWaTwo.webp': require('./data/Icons/God Info/jacob_s icons/nuWaTwo.webp'),
  'nuWaThree.webp': require('./data/Icons/God Info/jacob_s icons/nuWaThree.webp'),
  'nuWaFour.webp': require('./data/Icons/God Info/jacob_s icons/nuWaFour.webp'),
  'nuWaPassive.webp': require('./data/Icons/God Info/jacob_s icons/nuWaPassive.webp'),
  'odinImage.webp': require('./data/Icons/God Info/jacob_s icons/odinImage.webp'),
  'odinOne.webp': require('./data/Icons/God Info/jacob_s icons/odinOne.webp'),
  'odinTwo.webp': require('./data/Icons/God Info/jacob_s icons/odinTwo.webp'),
  'odinThree.webp': require('./data/Icons/God Info/jacob_s icons/odinThree.webp'),
  'odinFour.webp': require('./data/Icons/God Info/jacob_s icons/odinFour.webp'),
  'odinPassive.webp': require('./data/Icons/God Info/jacob_s icons/odinPassive.webp'),
  'osirisAspect.webp': require('./data/Icons/God Info/jacob_s icons/OsiAspect.webp'),
  'osirisImage.webp': require('./data/Icons/God Info/jacob_s icons/osirisImage.webp'),
  'osirisOne.webp': require('./data/Icons/God Info/jacob_s icons/osirisOne.webp'),
  'osirisTwo.webp': require('./data/Icons/God Info/jacob_s icons/osirisTwo.webp'),
  'osirisThree.webp': require('./data/Icons/God Info/jacob_s icons/osirisThree.webp'),
  'osirisFour.webp': require('./data/Icons/God Info/jacob_s icons/osirisFour.webp'),
  'osirisPassive.webp': require('./data/Icons/God Info/jacob_s icons/osirisPassive.webp'),
  'peleImage.webp': require('./data/Icons/God Info/jacob_s icons/peleImage.webp'),
  'peleOne.webp': require('./data/Icons/God Info/jacob_s icons/peleOne.webp'),
  'peleTwo.webp': require('./data/Icons/God Info/jacob_s icons/peleTwo.webp'),
  'peleThree.webp': require('./data/Icons/God Info/jacob_s icons/peleThree.webp'),
  'peleFour.webp': require('./data/Icons/God Info/jacob_s icons/peleFour.webp'),
  'pelePassive.webp': require('./data/Icons/God Info/jacob_s icons/pelePassive.webp'),
  'posImage.webp': require('./data/Icons/God Info/jacob_s icons/posImage.webp'),
  'posOne.webp': require('./data/Icons/God Info/jacob_s icons/posOne.webp'),
  'posTwo.webp': require('./data/Icons/God Info/jacob_s icons/posTwo.webp'),
  'posThree.webp': require('./data/Icons/God Info/jacob_s icons/posThree.webp'),
  'posFour.webp': require('./data/Icons/God Info/jacob_s icons/posFour.webp'),
  'posPassive.webp': require('./data/Icons/God Info/jacob_s icons/posPassive.webp'),
  'raImage.webp': require('./data/Icons/God Info/jacob_s icons/raImage.webp'),
  'raOne.webp': require('./data/Icons/God Info/jacob_s icons/raOne.webp'),
  'raTwo.webp': require('./data/Icons/God Info/jacob_s icons/raTwo.webp'),
  'raThree.webp': require('./data/Icons/God Info/jacob_s icons/raThree.webp'),
  'raFour.webp': require('./data/Icons/God Info/jacob_s icons/raFour.webp'),
  'raPassive.webp': require('./data/Icons/God Info/jacob_s icons/raPassive.webp'),
  'raAspect.webp': require('./data/Icons/God Info/jacob_s icons/raAspect.webp'),
  'ramaImage.webp': require('./data/Icons/God Info/jacob_s icons/ramaImage.webp'),
  'ramaOne.webp': require('./data/Icons/God Info/jacob_s icons/ramaOne.webp'),
  'ramaTwo.webp': require('./data/Icons/God Info/jacob_s icons/ramaTwo.webp'),
  'ramaThree.webp': require('./data/Icons/God Info/jacob_s icons/ramaThree.webp'),
  'ramaFour.webp': require('./data/Icons/God Info/jacob_s icons/ramaFour.webp'),
  'ramaPassive.webp': require('./data/Icons/God Info/jacob_s icons/ramaPassive.webp'),
  'ramaAspect.webp': require('./data/Icons/God Info/jacob_s icons/ramaAspect.webp'),
  'scyllaImage.webp': require('./data/Icons/God Info/jacob_s icons/scyllaImage.webp'),
  'scyllaOne.webp': require('./data/Icons/God Info/jacob_s icons/scyllaOne.webp'),
  'scyllaTwo.webp': require('./data/Icons/God Info/jacob_s icons/scyllaTwo.webp'),
  'scyllaThree.webp': require('./data/Icons/God Info/jacob_s icons/scyllaThree.webp'),
  'scyllaFour.webp': require('./data/Icons/God Info/jacob_s icons/scyllaFour.webp'),
  'scyllaPassive.webp': require('./data/Icons/God Info/jacob_s icons/scyllaPassive.webp'),
  'scyllaAspect.webp': require('./data/Icons/God Info/jacob_s icons/scyllaAspect.webp'),
  'sobekImage.webp': require('./data/Icons/God Info/jacob_s icons/sobekImage.webp'),
  'sobekOne.webp': require('./data/Icons/God Info/jacob_s icons/sobekOne.webp'),
  'sobekTwo.webp': require('./data/Icons/God Info/jacob_s icons/sobekTwo.webp'),
  'sobekThree.webp': require('./data/Icons/God Info/jacob_s icons/sobekThree.webp'),
  'sobekFour.webp': require('./data/Icons/God Info/jacob_s icons/sobekFour.webp'),
  'sobekPassive.webp': require('./data/Icons/God Info/jacob_s icons/sobekPassive.webp'),
  'sobekAspect.webp': require('./data/Icons/God Info/jacob_s icons/sobekAspect.webp'),
  'solImage.webp': require('./data/Icons/God Info/jacob_s icons/solImage.webp'),
  'solOne.webp': require('./data/Icons/God Info/jacob_s icons/solOne.webp'),
  'solTwo.webp': require('./data/Icons/God Info/jacob_s icons/solTwo.webp'),
  'solThree.webp': require('./data/Icons/God Info/jacob_s icons/solThree.webp'),
  'solFour.webp': require('./data/Icons/God Info/jacob_s icons/solFour.webp'),
  'solPassive.webp': require('./data/Icons/God Info/jacob_s icons/solPassive.webp'),
  'solAspect.webp': require('./data/Icons/God Info/jacob_s icons/solAspect.webp'),
  'susanoPassive.webp': require('./data/Icons/God Info/jacob_s icons/susPassive.webp'),
  'susanoImage.webp': require('./data/Icons/God Info/jacob_s icons/susanoImage.webp'),
  'susanoOne.webp': require('./data/Icons/God Info/jacob_s icons/susanoOne.webp'),
  'susanoTwo.webp': require('./data/Icons/God Info/jacob_s icons/susanoTwo.webp'),
  'susanoThree.webp': require('./data/Icons/God Info/jacob_s icons/susanoThree.webp'),
  'susanoFour.webp': require('./data/Icons/God Info/jacob_s icons/susanoFour.webp'),
  'sylvanusImage.webp': require('./data/Icons/God Info/jacob_s icons/sylvanusImage.webp'),
  'sylvanusOne.webp': require('./data/Icons/God Info/jacob_s icons/sylvanusOne.webp'),
  'sylvanusTwo.webp': require('./data/Icons/God Info/jacob_s icons/sylvanusTwo.webp'),
  'sylvanusThree.webp': require('./data/Icons/God Info/jacob_s icons/sylvanusThree.webp'),
  'sylvanusFour.webp': require('./data/Icons/God Info/jacob_s icons/sylvanusFour.webp'),
  'sylvanusPassive.webp': require('./data/Icons/God Info/jacob_s icons/sylvanusPassive.webp'),
  'sylvanusAspect.webp': require('./data/Icons/God Info/jacob_s icons/sylvanusAspect.webp'),
  'thanatosOne.webp': require('./data/Icons/God Info/jacob_s icons/thanaOne.webp'),
  'thanatosTwo.webp': require('./data/Icons/God Info/jacob_s icons/thanaTwo.webp'),
  'thanatosThree.webp': require('./data/Icons/God Info/jacob_s icons/thanaThree.webp'),
  'thanatosFour.webp': require('./data/Icons/God Info/jacob_s icons/thanaFour.webp'),
  'thanatosPassive.webp': require('./data/Icons/God Info/jacob_s icons/thanaPassive.webp'),
  'thanatosAspect.webp': require('./data/Icons/God Info/jacob_s icons/thanaAspect.webp'),
  'thanatosImage.webp': require('./data/Icons/God Info/jacob_s icons/thanatosImage.webp'),
  'thorImage.webp': require('./data/Icons/God Info/jacob_s icons/thorImage.webp'),
  'thorOne.webp': require('./data/Icons/God Info/jacob_s icons/thorOne.webp'),
  'thorTwo.webp': require('./data/Icons/God Info/jacob_s icons/thorTwo.webp'),
  'thorThree.webp': require('./data/Icons/God Info/jacob_s icons/thorThree.webp'),
  'thorFour.webp': require('./data/Icons/God Info/jacob_s icons/thorFour.webp'),
  'thorPassive.webp': require('./data/Icons/God Info/jacob_s icons/thorPassive.webp'),
  'thorAspect.webp': require('./data/Icons/God Info/jacob_s icons/thorAspect.webp'),
  'tsukuyomiAspect.webp': require('./data/Icons/God Info/jacob_s icons/tsukAspect.webp'),
  'tsukuImage.webp': require('./data/Icons/God Info/jacob_s icons/tsukuImage.webp'),
  'tsukuOne.webp': require('./data/Icons/God Info/jacob_s icons/tsukuOne.webp'),
  'tsukuTwo.webp': require('./data/Icons/God Info/jacob_s icons/tsukuTwo.webp'),
  'tsukuThree.webp': require('./data/Icons/God Info/jacob_s icons/tsukuThree.webp'),
  'tsukuFour.webp': require('./data/Icons/God Info/jacob_s icons/tsukuFour.webp'),
  'tsukuPassive.webp': require('./data/Icons/God Info/jacob_s icons/tsukuPassive.webp'),
  'ullrImage.webp': require('./data/Icons/God Info/jacob_s icons/ullrImage.webp'),
  'vulcanImage.webp': require('./data/Icons/God Info/jacob_s icons/vulcanImage.webp'),
  'vulcanOne.webp': require('./data/Icons/God Info/jacob_s icons/vulcanOne.webp'),
  'vulcanTwo.webp': require('./data/Icons/God Info/jacob_s icons/vulcanTwo.webp'),
  'vulcanThree.webp': require('./data/Icons/God Info/jacob_s icons/vulcanThree.webp'),
  'vulcanFour.webp': require('./data/Icons/God Info/jacob_s icons/vulcanFour.webp'),
  'vulcanPassive.webp': require('./data/Icons/God Info/jacob_s icons/vulcanPassive.webp'),
  'vulcanAspect.webp': require('./data/Icons/God Info/jacob_s icons/vulcanAspect.webp'),
  'wukongImage.webp': require('./data/Icons/God Info/jacob_s icons/wukongImage.webp'),
  'wukongOne.webp': require('./data/Icons/God Info/jacob_s icons/wukongOne.webp'),
  'wukongTwo.webp': require('./data/Icons/God Info/jacob_s icons/wukongTwo.webp'),
  'wukongThree.webp': require('./data/Icons/God Info/jacob_s icons/wukongThree.webp'),
  'wukongFour.webp': require('./data/Icons/God Info/jacob_s icons/wukongFour.webp'),
  'wukongPassive.webp': require('./data/Icons/God Info/jacob_s icons/wukongPassive.webp'),
  'xbalImage.webp': require('./data/Icons/God Info/jacob_s icons/xbalImage.webp'),
  'xbalOne.webp': require('./data/Icons/God Info/jacob_s icons/xbalOne.webp'),
  'xbalFour.webp': require('./data/Icons/God Info/jacob_s icons/xbalFour.webp'),
  'xbalPassive.webp': require('./data/Icons/God Info/jacob_s icons/xbalPassive.webp'),
  'yemImage.webp': require('./data/Icons/God Info/jacob_s icons/yemImage.webp'),
  'yemTwo.webp': require('./data/Icons/God Info/jacob_s icons/yemTwo.webp'),
  'yemThree.webp': require('./data/Icons/God Info/jacob_s icons/yemThree.webp'),
  'yemFour.webp': require('./data/Icons/God Info/jacob_s icons/yemFour.webp'),
  'yemPassive.webp': require('./data/Icons/God Info/jacob_s icons/yemPassive.webp'),
  'yemAspect.webp': require('./data/Icons/God Info/jacob_s icons/yemAspect.webp'),
  'ymirImage.webp': require('./data/Icons/God Info/jacob_s icons/ymirImage.webp'),
  'ymirOne.webp': require('./data/Icons/God Info/jacob_s icons/ymirOne.webp'),
  'ymirTwo.webp': require('./data/Icons/God Info/jacob_s icons/ymirTwo.webp'),
  'ymirThree.webp': require('./data/Icons/God Info/jacob_s icons/ymirThree.webp'),
  'ymirFour.webp': require('./data/Icons/God Info/jacob_s icons/ymirFour.webp'),
  'ymirPassive.webp': require('./data/Icons/God Info/jacob_s icons/ymirPassive.webp'),
  'zeusImage.webp': require('./data/Icons/God Info/jacob_s icons/zeusImage.webp'),
  'zeusOne.webp': require('./data/Icons/God Info/jacob_s icons/zeusOne.webp'),
  'zeusTwo.webp': require('./data/Icons/God Info/jacob_s icons/zeusTwo.webp'),
  'zeusThree.webp': require('./data/Icons/God Info/jacob_s icons/zeusThree.webp'),
  'zeusFour.webp': require('./data/Icons/God Info/jacob_s icons/zeusFour.webp'),
  'zeusPassive.webp': require('./data/Icons/God Info/jacob_s icons/zeusPassive.webp'),
 };

// Case-insensitive lookup helper for god assets.
const godAssetMapLower = {};
for (const key of Object.keys(godAssetMap)) {
  godAssetMapLower[key.toLowerCase()] = godAssetMap[key];
}

export function getLocalGodAsset(iconPath) {
  if (!iconPath) return null;
  const base = iconPath.split('/').pop() || '';
  return godAssetMap[base] || godAssetMapLower[base.toLowerCase()] || null;
}

// Dummy default export so Expo Router / navigation stops treating this as a missing-route component.
// This is NOT used as a screen; it just silences the "missing default export" warning.
export default function LocalIconsConfig() {
  return null;
}

