/** Auto-generated by scripts/generate-patch-notes-loader.js — do not edit by hand */
const OPEN_BETA_PATCH_FILES = {
  1: require('../app/data/Patch Notes/patchnotesob1.json'),
  2: require('../app/data/Patch Notes/patchnotesob2.json'),
  3: require('../app/data/Patch Notes/patchnotesob3.json'),
  4: require('../app/data/Patch Notes/patchnotesob4.json'),
  5: require('../app/data/Patch Notes/patchnotesob5.json'),
  6: require('../app/data/Patch Notes/patchnotesob6.json'),
  7: require('../app/data/Patch Notes/patchnotesob7.json'),
  8: require('../app/data/Patch Notes/patchnotesob8.json'),
  9: require('../app/data/Patch Notes/patchnotesob9.json'),
  10: require('../app/data/Patch Notes/patchnotesob10.json'),
  11: require('../app/data/Patch Notes/patchnotesob11.json'),
  12: require('../app/data/Patch Notes/patchnotesob12.json'),
  13: require('../app/data/Patch Notes/patchnotesob13.json'),
  14: require('../app/data/Patch Notes/patchnotesob14.json'),
  15: require('../app/data/Patch Notes/patchnotesob15.json'),
  16: require('../app/data/Patch Notes/patchnotesob16.json'),
  17: require('../app/data/Patch Notes/patchnotesob17.json'),
  18: require('../app/data/Patch Notes/patchnotesob18.json'),
  19: require('../app/data/Patch Notes/patchnotesob19.json'),
  20: require('../app/data/Patch Notes/patchnotesob20.json'),
  21: require('../app/data/Patch Notes/patchnotesob21.json'),
  22: require('../app/data/Patch Notes/patchnotesob22.json'),
  23: require('../app/data/Patch Notes/patchnotesob23.json'),
  24: require('../app/data/Patch Notes/patchnotesob24.json'),
  25: require('../app/data/Patch Notes/patchnotesob25.json'),
  26: require('../app/data/Patch Notes/patchnotesob26.json'),
  27: require('../app/data/Patch Notes/patchnotesob27.json'),
  28: require('../app/data/Patch Notes/patchnotesob28.json'),
  29: require('../app/data/Patch Notes/patchnotesob29.json'),
  30: require('../app/data/Patch Notes/patchnotesob30.json'),
  31: require('../app/data/Patch Notes/patchnotesob31.json'),
  32: require('../app/data/Patch Notes/patchnotesob32.json'),
  33: require('../app/data/Patch Notes/patchnotesob33.json'),
  34: require('../app/data/Patch Notes/patchnotesob34.json'),
  35: require('../app/data/Patch Notes/patchnotesob35.json'),
  36: require('../app/data/Patch Notes/patchnotesob36.json'),
  37: require('../app/data/Patch Notes/patchnotesob37.json'),
  38: require('../app/data/Patch Notes/patchnotesob38.json'),
};

function loadOpenBetaPatch(patchNumber) {
  return OPEN_BETA_PATCH_FILES[patchNumber] ?? null;
}

module.exports = {
  OPEN_BETA_PATCH_FILES,
  loadOpenBetaPatch,
};
