/**
 * Shop data: rarities, challenges, and item pool.
 * All currency is Gold (earned via daily login + challenges). No real money.
 */

// Smite-themed rarities — achievable, not punishing
export const SHOP_RARITIES = {
  common: {
    key: 'common',
    label: 'Common',
    color: '#94a3b8',
    borderColor: '#64748b',
    bgGlow: 'rgba(100, 116, 139, 0.2)',
    weight: 40,
  },
  uncommon: {
    key: 'uncommon',
    label: 'Uncommon',
    color: '#22c55e',
    borderColor: '#16a34a',
    bgGlow: 'rgba(34, 197, 94, 0.2)',
    weight: 30,
  },
  rare: {
    key: 'rare',
    label: 'Rare',
    color: '#3b82f6',
    borderColor: '#2563eb',
    bgGlow: 'rgba(59, 130, 246, 0.25)',
    weight: 18,
  },
  epic: {
    key: 'epic',
    label: 'Epic',
    color: '#a855f7',
    borderColor: '#9333ea',
    bgGlow: 'rgba(168, 85, 247, 0.3)',
    weight: 9,
  },
  legendary: {
    key: 'legendary',
    label: 'Legendary',
    color: '#f59e0b',
    borderColor: '#d97706',
    bgGlow: 'rgba(245, 158, 11, 0.35)',
    weight: 3,
  },
};

export const CHALLENGES = [
  { id: 'daily_login', name: 'Daily Login', description: 'Log in to the app today', goldReward: 50, condition: 'daily_login', repeatable: true },
  { id: 'wordle_win', name: 'God Wordle Win', description: 'Win a game of God Wordle', goldReward: 75, condition: 'wordle_win', repeatable: true },
  { id: 'ability_win', name: 'Guess the Ability Win', description: 'Win a game of Guess the Ability', goldReward: 75, condition: 'ability_win', repeatable: true },
  { id: 'save_build', name: 'Save a Build', description: 'Save a build from Custom Builder', goldReward: 100, condition: 'save_build', repeatable: true },
  { id: 'first_build', name: 'First Build', description: 'Save your first build ever', goldReward: 150, condition: 'first_build', repeatable: false },
  { id: 'profile_theme', name: 'Customize Profile', description: 'Set a profile color or name effect', goldReward: 50, condition: 'profile_theme', repeatable: false },
  { id: 'share_profile', name: 'Share Profile', description: 'Share your profile link', goldReward: 25, condition: 'share_profile', repeatable: true },
];

// Full pool: name_fx value must exist in profile NAME_ANIMATION_OPTIONS. font value = key in PROFILE_FONT_FAMILY_MAP.
export const SHOP_ITEM_POOL = [
  // —— Name FX
  { id: 'name_fx_flame', type: 'name_fx', value: 'flame', name: 'Flame', description: 'Flickering fire', rarity: 'uncommon', cost: 120 },
  { id: 'name_fx_inferno', type: 'name_fx', value: 'inferno', name: 'Inferno', description: 'Intense fire', rarity: 'rare', cost: 200 },
  { id: 'name_fx_ember', type: 'name_fx', value: 'ember', name: 'Ember', description: 'Warm ember glow', rarity: 'common', cost: 80 },
  { id: 'name_fx_void', type: 'name_fx', value: 'void', name: 'Void', description: 'Dark purple shift', rarity: 'rare', cost: 200 },
  { id: 'name_fx_arcane', type: 'name_fx', value: 'arcane', name: 'Arcane', description: 'Magical pulse', rarity: 'uncommon', cost: 140 },
  { id: 'name_fx_divine', type: 'name_fx', value: 'divine', name: 'Celestial Wrath', description: 'Divine gold', rarity: 'epic', cost: 350 },
  { id: 'name_fx_storm', type: 'name_fx', value: 'storm', name: 'Stormforged Arc', description: 'Storm lightning', rarity: 'epic', cost: 350 },
  { id: 'name_fx_pantheon_greek', type: 'name_fx', value: 'pantheon_greek', name: 'Pantheon: Greek', description: 'Greek theme', rarity: 'rare', cost: 220 },
  { id: 'name_fx_pantheon_norse', type: 'name_fx', value: 'pantheon_norse', name: 'Pantheon: Norse', description: 'Norse theme', rarity: 'rare', cost: 220 },
  { id: 'name_fx_pantheon_egyptian', type: 'name_fx', value: 'pantheon_egyptian', name: 'Pantheon: Egyptian', description: 'Egyptian theme', rarity: 'rare', cost: 220 },
  { id: 'name_fx_gradient', type: 'name_fx', value: 'gradient', name: 'Olympian Flux', description: 'Flowing gradient', rarity: 'common', cost: 90, defaultUnlocked: true },
  { id: 'name_fx_pulse', type: 'name_fx', value: 'pulse', name: 'Godspark Pulse', description: 'Soft pulse', rarity: 'common', cost: 70, defaultUnlocked: true },
  { id: 'name_fx_shimmer', type: 'name_fx', value: 'shimmer', name: 'Aegis Glint', description: 'Shimmer', rarity: 'uncommon', cost: 110, defaultUnlocked: true },
  { id: 'name_fx_neon', type: 'name_fx', value: 'neon', name: 'Neon', description: 'Glowing neon', rarity: 'rare', cost: 220 },
  { id: 'name_fx_comic', type: 'name_fx', value: 'comic', name: 'Comic', description: 'Pop-art style', rarity: 'uncommon', cost: 130 },
  { id: 'name_fx_metallic', type: 'name_fx', value: 'metallic', name: 'Metallic', description: 'Chrome sheen', rarity: 'epic', cost: 340 },
  { id: 'name_fx_ice', type: 'name_fx', value: 'ice', name: 'Ice', description: 'Frosted crystal', rarity: 'rare', cost: 210 },
  { id: 'name_fx_glow', type: 'name_fx', value: 'glow', name: 'Dark Magic', description: 'Purple mystic glow', rarity: 'rare', cost: 200 },
  { id: 'name_fx_lava', type: 'name_fx', value: 'lava', name: 'Lava', description: 'Molten flow', rarity: 'epic', cost: 330 },
  { id: 'name_fx_shadow_dance', type: 'name_fx', value: 'shadow_dance', name: 'Dancing Shadow', description: 'Moving shadow', rarity: 'uncommon', cost: 100 },
  { id: 'name_fx_glow_breath', type: 'name_fx', value: 'glow_breath', name: 'Breathing Glow', description: 'Pulsing glow', rarity: 'rare', cost: 190 },
  { id: 'name_fx_outline_pulse', type: 'name_fx', value: 'outline_pulse', name: 'Outline Pulse', description: 'Pulsing outline', rarity: 'uncommon', cost: 115 },
  { id: 'name_fx_frost', type: 'name_fx', value: 'frost', name: 'Frost', description: 'Frosted glass', rarity: 'rare', cost: 185 },
  // —— Fonts (value = font key in PROFILE_FONT_FAMILY_MAP)
  { id: 'font_serif', type: 'font', value: 'serif', name: 'Serif', description: 'Classic serif', rarity: 'common', cost: 50, defaultUnlocked: true },
  { id: 'font_rounded', type: 'font', value: 'rounded', name: 'Rounded', description: 'Soft rounded', rarity: 'common', cost: 60 },
  { id: 'font_condensed', type: 'font', value: 'condensed', name: 'Condensed', description: 'Narrow style', rarity: 'uncommon', cost: 90 },
  { id: 'font_comic', type: 'font', value: 'comic', name: 'Comic Sans', description: 'Casual comic', rarity: 'uncommon', cost: 85 },
  { id: 'font_elegant', type: 'font', value: 'elegant', name: 'Elegant', description: 'Elegant script', rarity: 'rare', cost: 170 },
  { id: 'font_royal', type: 'font', value: 'royal', name: 'Royal', description: 'Ornate royal', rarity: 'rare', cost: 180 },
  { id: 'font_strong', type: 'font', value: 'strong', name: 'Strong', description: 'Heavy bold', rarity: 'uncommon', cost: 95 },
  { id: 'font_narrow', type: 'font', value: 'narrow', name: 'Narrow', description: 'Sleek narrow', rarity: 'common', cost: 55 },
  { id: 'font_wide', type: 'font', value: 'wide', name: 'Wide', description: 'Wide stretched', rarity: 'uncommon', cost: 88 },
  { id: 'font_mono', type: 'font', value: 'mono', name: 'Mono', description: 'Code / terminal', rarity: 'common', cost: 65 },
  { id: 'font_mythic', type: 'font', value: 'mythic', name: 'Mythic', description: 'Ancient legend', rarity: 'rare', cost: 175 },
  { id: 'font_mystic', type: 'font', value: 'mystic', name: 'Mystic', description: 'Mysterious aura', rarity: 'rare', cost: 168 },
  { id: 'font_oracle', type: 'font', value: 'oracle', name: 'Oracle', description: 'Prophetic style', rarity: 'epic', cost: 280 },
  { id: 'font_rune', type: 'font', value: 'rune', name: 'Rune', description: 'Runic carving', rarity: 'rare', cost: 195 },
  { id: 'font_titan', type: 'font', value: 'titan', name: 'Titan', description: 'Titan strength', rarity: 'epic', cost: 290 },
  { id: 'font_celestial', type: 'font', value: 'celestial', name: 'Celestial', description: 'Divine script', rarity: 'epic', cost: 300 },
  { id: 'font_shadow', type: 'font', value: 'shadow', name: 'Shadow', description: 'Dark edge', rarity: 'uncommon', cost: 98 },
  { id: 'font_ancient', type: 'font', value: 'ancient', name: 'Ancient', description: 'Old world', rarity: 'rare', cost: 182 },
  { id: 'font_gothic', type: 'font', value: 'gothic', name: 'Gothic', description: 'Gothic style', rarity: 'uncommon', cost: 102 },
  { id: 'font_script', type: 'font', value: 'script', name: 'Script', description: 'Handwritten', rarity: 'rare', cost: 165 },
  { id: 'font_bold', type: 'font', value: 'bold', name: 'Bold', description: 'Heavy weight', rarity: 'common', cost: 58 },
  { id: 'font_light', type: 'font', value: 'light', name: 'Light', description: 'Thin weight', rarity: 'common', cost: 52 },
  { id: 'font_stencil', type: 'font', value: 'stencil', name: 'Stencil', description: 'Stencil cut', rarity: 'uncommon', cost: 92 },
  { id: 'font_retro', type: 'font', value: 'retro', name: 'Retro', description: 'Retro vibe', rarity: 'uncommon', cost: 88 },
  { id: 'font_tech', type: 'font', value: 'tech', name: 'Tech', description: 'Tech future', rarity: 'rare', cost: 178 },
  { id: 'font_cosmic', type: 'font', value: 'cosmic', name: 'Cosmic', description: 'Space style', rarity: 'epic', cost: 310 },
  { id: 'font_dragon', type: 'font', value: 'dragon', name: 'Dragon', description: 'Dragon fire', rarity: 'legendary', cost: 420 },
  { id: 'font_phoenix', type: 'font', value: 'phoenix', name: 'Phoenix', description: 'Rebirth flame', rarity: 'legendary', cost: 440 },
  { id: 'font_olympian', type: 'font', value: 'olympian', name: 'Olympian', description: 'Godly script', rarity: 'epic', cost: 295 },
  { id: 'font_egyptian', type: 'font', value: 'egyptian', name: 'Egyptian', description: 'Desert king', rarity: 'epic', cost: 285 },
  { id: 'font_norse', type: 'font', value: 'norse', name: 'Norse', description: 'Frost runes', rarity: 'epic', cost: 278 },
  // Extra wacky / crazy styles
  { id: 'font_graffiti', type: 'font', value: 'graffiti', name: 'Graffiti', description: 'Street spray', rarity: 'epic', cost: 305 },
  { id: 'font_glitch', type: 'font', value: 'glitch', name: 'Glitch', description: 'Broken pixels', rarity: 'epic', cost: 310 },
  { id: 'font_slime', type: 'font', value: 'slime', name: 'Slime', description: 'Dripping ooze', rarity: 'rare', cost: 210 },
  { id: 'font_toxic', type: 'font', value: 'toxic', name: 'Toxic', description: 'Hazard neon', rarity: 'epic', cost: 295 },
  { id: 'font_arcade', type: 'font', value: 'arcade', name: 'Arcade', description: 'Retro arcade', rarity: 'rare', cost: 200 },
  { id: 'font_pixel', type: 'font', value: 'pixel', name: 'Pixel', description: 'Blocky pixels', rarity: 'rare', cost: 205 },
  { id: 'font_spooky', type: 'font', value: 'spooky', name: 'Spooky', description: 'Haunted script', rarity: 'epic', cost: 320 },
  // System-inspired styles from desktop font gallery
  { id: 'font_agency_fb', type: 'font', value: 'agency_fb', name: 'Agency FB', description: 'Tall condensed', rarity: 'rare', cost: 210 },
  { id: 'font_algerian', type: 'font', value: 'algerian', name: 'Algerian', description: 'Engraved display', rarity: 'epic', cost: 260 },
  { id: 'font_bahnschrift', type: 'font', value: 'bahnschrift', name: 'Bahnschrift', description: 'Modern grotesk', rarity: 'rare', cost: 190 },
  { id: 'font_baskerville_old', type: 'font', value: 'baskerville_old', name: 'Baskerville Old', description: 'Classic book serif', rarity: 'rare', cost: 200 },
  { id: 'font_bauhaus', type: 'font', value: 'bauhaus', name: 'Bauhaus 93', description: 'Rounded retro', rarity: 'epic', cost: 255 },
  { id: 'font_bell_mt', type: 'font', value: 'bell_mt', name: 'Bell MT', description: 'Elegant serif', rarity: 'rare', cost: 195 },
  { id: 'font_berlin_sans', type: 'font', value: 'berlin_sans', name: 'Berlin Sans', description: 'Geometric sans', rarity: 'uncommon', cost: 140 },
  { id: 'font_bernard', type: 'font', value: 'bernard', name: 'Bernard MT', description: 'Chunky display', rarity: 'epic', cost: 270 },
  { id: 'font_blackadder', type: 'font', value: 'blackadder', name: 'Blackadder', description: 'Spiky gothic script', rarity: 'legendary', cost: 420 },
  { id: 'font_bodoni_mt', type: 'font', value: 'bodoni_mt', name: 'Bodoni MT', description: 'High-contrast serif', rarity: 'rare', cost: 215 },
  { id: 'font_book_antiqua', type: 'font', value: 'book_antiqua', name: 'Book Antiqua', description: 'Readable serif', rarity: 'common', cost: 90 },
  { id: 'font_bookman_old', type: 'font', value: 'bookman_old', name: 'Bookman Old', description: 'Old-style serif', rarity: 'uncommon', cost: 130 },
  { id: 'font_bradley_hand', type: 'font', value: 'bradley_hand', name: 'Bradley Hand', description: 'Casual hand', rarity: 'rare', cost: 205 },
  { id: 'font_britannic', type: 'font', value: 'britannic', name: 'Britannic', description: 'Industrial display', rarity: 'rare', cost: 215 },
  { id: 'font_broadway', type: 'font', value: 'broadway', name: 'Broadway', description: 'Theatre marquee', rarity: 'epic', cost: 285 },
  { id: 'font_brush_script', type: 'font', value: 'brush_script', name: 'Brush Script', description: 'Painted script', rarity: 'rare', cost: 210 },
  { id: 'font_calibri', type: 'font', value: 'calibri', name: 'Calibri', description: 'Modern UI', rarity: 'common', cost: 80 },
  { id: 'font_cambria', type: 'font', value: 'cambria', name: 'Cambria', description: 'Clear serif', rarity: 'common', cost: 85 },
  { id: 'font_castellar', type: 'font', value: 'castellar', name: 'Castellar', description: 'Stone carved', rarity: 'epic', cost: 290 },
  { id: 'font_niagara_engraved', type: 'font', value: 'niagara_engraved', name: 'Niagara Engraved', description: 'Tall engraved', rarity: 'epic', cost: 260 },
  { id: 'font_niagara_solid', type: 'font', value: 'niagara_solid', name: 'Niagara Solid', description: 'Tall solid', rarity: 'rare', cost: 210 },
  { id: 'font_old_english', type: 'font', value: 'old_english', name: 'Old English', description: 'Blackletter', rarity: 'legendary', cost: 430 },
  { id: 'font_onyx', type: 'font', value: 'onyx', name: 'Onyx', description: 'Ultra condensed', rarity: 'rare', cost: 205 },
  { id: 'font_palace_script', type: 'font', value: 'palace_script', name: 'Palace Script', description: 'Royal script', rarity: 'epic', cost: 275 },
  { id: 'font_palatino', type: 'font', value: 'palatino', name: 'Palatino', description: 'Book serif', rarity: 'rare', cost: 200 },
  { id: 'font_papyrus', type: 'font', value: 'papyrus', name: 'Papyrus', description: 'Rough papyrus', rarity: 'epic', cost: 300 },
  { id: 'font_parchment', type: 'font', value: 'parchment', name: 'Parchment', description: 'Fantasy scroll', rarity: 'epic', cost: 295 },
  { id: 'font_perpetua', type: 'font', value: 'perpetua', name: 'Perpetua', description: 'Elegant book', rarity: 'rare', cost: 210 },
  { id: 'font_playbill', type: 'font', value: 'playbill', name: 'Playbill', description: 'Poster display', rarity: 'epic', cost: 285 },
  { id: 'font_edwardian', type: 'font', value: 'edwardian', name: 'Edwardian Script', description: 'Formal script', rarity: 'legendary', cost: 440 },
  { id: 'font_elephant', type: 'font', value: 'elephant', name: 'Elephant', description: 'Heavy serif', rarity: 'epic', cost: 280 },
  { id: 'font_engravers', type: 'font', value: 'engravers', name: 'Engravers', description: 'Engraved caps', rarity: 'epic', cost: 290 },
  { id: 'font_felix', type: 'font', value: 'felix', name: 'Felix Titling', description: 'All-caps display', rarity: 'epic', cost: 270 },
  { id: 'font_forte', type: 'font', value: 'forte', name: 'Forte', description: 'Bouncy display', rarity: 'rare', cost: 215 },
  { id: 'font_franklin_book', type: 'font', value: 'franklin_book', name: 'Franklin Gothic Book', description: 'Workhorse sans', rarity: 'uncommon', cost: 140 },
  { id: 'font_freestyle', type: 'font', value: 'freestyle', name: 'Freestyle Script', description: 'Loose script', rarity: 'rare', cost: 210 },
  { id: 'font_french_script', type: 'font', value: 'french_script', name: 'French Script', description: 'Thin script', rarity: 'epic', cost: 275 },
  { id: 'font_gabriola', type: 'font', value: 'gabriola', name: 'Gabriola', description: 'Calligraphic', rarity: 'epic', cost: 280 },
  { id: 'font_gadugi', type: 'font', value: 'gadugi', name: 'Gadugi', description: 'UI sans', rarity: 'common', cost: 85 },
  { id: 'font_garamond', type: 'font', value: 'garamond', name: 'Garamond', description: 'Classic serif', rarity: 'rare', cost: 205 },
  { id: 'font_gigi', type: 'font', value: 'gigi', name: 'Gigi', description: 'Playful script', rarity: 'rare', cost: 215 },
  { id: 'font_sylfaen', type: 'font', value: 'sylfaen', name: 'Sylfaen', description: 'Humanist serif', rarity: 'rare', cost: 205 },
  { id: 'font_tempus', type: 'font', value: 'tempus', name: 'Tempus Sans', description: 'Casual sans', rarity: 'rare', cost: 200 },
  { id: 'font_times_new', type: 'font', value: 'times_new', name: 'Times New Roman', description: 'Newspaper serif', rarity: 'common', cost: 75 },
  { id: 'font_trajan', type: 'font', value: 'trajan', name: 'Trajan Pro', description: 'Roman carved', rarity: 'legendary', cost: 450 },
  { id: 'font_trebuchet', type: 'font', value: 'trebuchet', name: 'Trebuchet MS', description: 'Friendly sans', rarity: 'common', cost: 90 },
  { id: 'font_tw_cen', type: 'font', value: 'tw_cen', name: 'Tw Cen MT', description: 'Twentieth century', rarity: 'rare', cost: 210 },
  { id: 'font_verdana', type: 'font', value: 'verdana', name: 'Verdana', description: 'Screen sans', rarity: 'common', cost: 80 },
  { id: 'font_viner', type: 'font', value: 'viner', name: 'Viner Hand', description: 'Rough hand', rarity: 'epic', cost: 290 },
  { id: 'font_vivaldi', type: 'font', value: 'vivaldi', name: 'Vivaldi', description: 'Flourished script', rarity: 'epic', cost: 295 },
  { id: 'font_vladimir', type: 'font', value: 'vladimir', name: 'Vladimir Script', description: 'Heavy script', rarity: 'epic', cost: 295 },
  { id: 'font_wide_latin', type: 'font', value: 'wide_latin', name: 'Wide Latin', description: 'Ultra wide', rarity: 'legendary', cost: 460 },
  // —— Titles
  { id: 'title_ascended', type: 'title', value: 'Ascended', name: 'Title: Ascended', description: 'Under your name', rarity: 'common', cost: 60, defaultUnlocked: true },
  { id: 'title_conqueror', type: 'title', value: 'Conqueror', name: 'Title: Conqueror', description: 'Under your name', rarity: 'uncommon', cost: 100 },
  { id: 'title_legend', type: 'title', value: 'Legend', name: 'Title: Legend', description: 'Under your name', rarity: 'rare', cost: 180 },
  { id: 'title_olympian', type: 'title', value: 'Olympian', name: 'Title: Olympian', description: 'Under your name', rarity: 'epic', cost: 320 },
  { id: 'title_divine', type: 'title', value: 'Divine', name: 'Title: Divine', description: 'Under your name', rarity: 'legendary', cost: 500 },
  { id: 'title_master_builder', type: 'title', value: 'Master Builder', name: 'Title: Master Builder', description: 'Under your name', rarity: 'rare', cost: 200 },
  { id: 'title_patch_reader', type: 'title', value: 'Patch Reader', name: 'Title: Patch Reader', description: 'Under your name', rarity: 'common', cost: 50, defaultUnlocked: true },
  { id: 'title_warden', type: 'title', value: 'Warden', name: 'Title: Warden', description: 'Under your name', rarity: 'uncommon', cost: 95 },
  { id: 'title_titan', type: 'title', value: 'Titan', name: 'Title: Titan', description: 'Under your name', rarity: 'epic', cost: 340 },
  { id: 'title_oracle', type: 'title', value: 'Oracle', name: 'Title: Oracle', description: 'Under your name', rarity: 'rare', cost: 210 },
  { id: 'title_phoenix', type: 'title', value: 'Phoenix', name: 'Title: Phoenix', description: 'Under your name', rarity: 'legendary', cost: 520 },
  { id: 'title_dragon_slayer', type: 'title', value: 'Dragon Slayer', name: 'Title: Dragon Slayer', description: 'Under your name', rarity: 'epic', cost: 360 },
  { id: 'title_godspark', type: 'title', value: 'Godspark', name: 'Title: Godspark', description: 'Under your name', rarity: 'rare', cost: 195 },
  { id: 'title_mythic', type: 'title', value: 'Mythic', name: 'Title: Mythic', description: 'Under your name', rarity: 'epic', cost: 330 },
  { id: 'title_arcane', type: 'title', value: 'Arcane', name: 'Title: Arcane', description: 'Under your name', rarity: 'uncommon', cost: 110 },
  { id: 'title_void_walker', type: 'title', value: 'Void Walker', name: 'Title: Void Walker', description: 'Under your name', rarity: 'rare', cost: 220 },
  { id: 'title_stormcaller', type: 'title', value: 'Stormcaller', name: 'Title: Stormcaller', description: 'Under your name', rarity: 'epic', cost: 350 },
  { id: 'title_immortal', type: 'title', value: 'Immortal', name: 'Title: Immortal', description: 'Under your name', rarity: 'legendary', cost: 550 },
  { id: 'title_champion', type: 'title', value: 'Champion', name: 'Title: Champion', description: 'Under your name', rarity: 'rare', cost: 205 },
  { id: 'title_elder', type: 'title', value: 'Elder', name: 'Title: Elder', description: 'Under your name', rarity: 'uncommon', cost: 105 },
  { id: 'title_adept', type: 'title', value: 'Adept', name: 'Title: Adept', description: 'Under your name', rarity: 'common', cost: 65 },
  // —— Sponsored
  { id: 'feature_sponsored', type: 'sponsored', value: 'sponsored', name: 'Featured Streamer', description: 'Twitch on More page', rarity: 'legendary', cost: 800 },
];

export const FREE_REROLLS_PER_DAY = 5;
export const SHOP_SLOT_COUNT = 6;
export const DAILY_GOLD_AMOUNT = 50;
