/**
 * Shared cyan dark-shell tokens + floating chrome styles.
 * Canonical reference: Builds ability tooltip (`lib/KitAbilityTooltipModal.jsx`).
 */
import { StyleSheet } from 'react-native';

/** Color + layout tokens for modals, tooltips, dropdowns, and inset panels. */
export const UI_THEME = {
  borderCyan: 'rgba(125, 211, 252, 0.42)',
  borderCyanSoft: 'rgba(125, 211, 252, 0.14)',
  borderCyanFill10: 'rgba(125, 211, 252, 0.10)',
  borderCyanFill12: 'rgba(125, 211, 252, 0.12)',
  borderCyanFill08: 'rgba(125, 211, 252, 0.08)',
  cardBg: 'rgba(8, 12, 22, 0.98)',
  overlayScrim: 'rgba(3, 7, 18, 0.42)',
  panelBg: '#0b1220',
  panelBgAlt: '#0f1724',
  panelBgSection: '#0b1226',
  panelBorder: '#1e3a5f',
  panelBorderMuted: '#1e293b',
  mediaBg: '#030712',
  accentSky: '#7dd3fc',
  labelSoft: '#93c5fd',
  textPrimary: '#f1f5f9',
  textBright: '#f8fafc',
  textBody: '#cbd5e1',
  textMuted: '#94a3b8',
  textHint: '#64748b',
  textClose: '#e6eef8',
  textIconFallback: '#e2e8f0',
  textDropdown: '#e6eef8',
  statDelta: '#67e8f9',
  radiusCard: 10,
  radiusPanel: 8,
  radiusClose: 14,
  shadowCard: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 8,
  },
  shadowClose: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
  },
};

/** Default pantheon-agnostic tooltip border (Builds modal default). */
export const UI_TOOLTIP_BORDER_DEFAULT = UI_THEME.borderCyan;

/**
 * Kit ability tooltip modal — shared by Builds (`KitAbilityTooltipModal`)
 * and Database god kit (via `kitAbilityTooltipStylesForData` aliases).
 */
export const kitAbilityTooltipModalStyles = StyleSheet.create({
  overlayRoot: {
    flex: 1,
    backgroundColor: UI_THEME.overlayScrim,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardWrap: {
    zIndex: 4,
    elevation: 10,
    overflow: 'visible',
    width: '100%',
  },
  card: {
    width: '100%',
    backgroundColor: UI_THEME.cardBg,
    borderWidth: 1,
    borderColor: UI_THEME.borderCyan,
    borderRadius: UI_THEME.radiusCard,
    padding: 12,
    alignSelf: 'center',
    ...UI_THEME.shadowCard,
    overflow: 'hidden',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 6,
    marginBottom: 6,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    minWidth: 0,
    gap: 8,
  },
  iconWrap: {
    width: 32,
    height: 32,
    borderRadius: UI_THEME.radiusPanel,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: UI_THEME.panelBorder,
    backgroundColor: UI_THEME.panelBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  icon: {
    width: '100%',
    height: '100%',
  },
  iconFallback: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconFallbackText: {
    color: UI_THEME.textIconFallback,
    fontSize: 14,
    fontWeight: '800',
  },
  titleWrap: {
    flex: 1,
    minWidth: 0,
  },
  title: {
    color: UI_THEME.textPrimary,
    fontWeight: '800',
    fontSize: 14,
    lineHeight: 18,
  },
  subTitle: {
    marginTop: 1,
    color: UI_THEME.accentSky,
    fontSize: 8,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  compactSubtitle: {
    marginTop: 2,
    marginBottom: 0,
    color: UI_THEME.textMuted,
    fontSize: 10,
    lineHeight: 14,
    fontStyle: 'italic',
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
    flexShrink: 0,
  },
  closeCornerBtn: {
    position: 'absolute',
    top: -12,
    right: -8,
    width: 28,
    height: 28,
    borderRadius: UI_THEME.radiusClose,
    backgroundColor: UI_THEME.panelBorder,
    borderWidth: 1,
    borderColor: UI_THEME.borderCyan,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 20,
    elevation: 14,
    ...UI_THEME.shadowClose,
  },
  closeCornerText: {
    color: UI_THEME.textClose,
    fontSize: 22,
    fontWeight: '700',
    lineHeight: 24,
    marginTop: -2,
  },
  sectionLabel: {
    color: UI_THEME.labelSoft,
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 0.2,
    marginBottom: 2,
  },
  levelStepperTopRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderWidth: 1,
    borderColor: 'rgba(125, 211, 252, 0.35)',
    borderRadius: 8,
    paddingVertical: 4,
    paddingHorizontal: 5,
    backgroundColor: 'rgba(11, 18, 32, 0.95)',
  },
  levelStepperBtn: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: UI_THEME.panelBorder,
    backgroundColor: UI_THEME.panelBgAlt,
    alignItems: 'center',
    justifyContent: 'center',
  },
  levelStepperText: {
    color: UI_THEME.textBody,
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 15,
    marginTop: -1,
  },
  levelStepperTextDisabled: {
    color: UI_THEME.textHint,
  },
  levelCurrentText: {
    color: UI_THEME.accentSky,
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 14,
    minWidth: 16,
    textAlign: 'center',
  },
  talentSummarySection: {
    marginBottom: 2,
  },
  talentChangesSection: {
    flexShrink: 0,
  },
  talentAbilityBlock: {
    marginTop: 8,
    paddingTop: 6,
    borderTopWidth: 1,
    borderTopColor: UI_THEME.panelBorderMuted,
  },
  talentAbilityTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
    flexWrap: 'wrap',
  },
  talentAbilityIconWrap: {
    width: 22,
    height: 22,
    borderRadius: 5,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: UI_THEME.panelBorder,
    backgroundColor: UI_THEME.panelBg,
    flexShrink: 0,
  },
  talentAbilityIcon: {
    width: '100%',
    height: '100%',
  },
  talentAbilityTitle: {
    color: UI_THEME.textPrimary,
    fontWeight: '700',
    flexShrink: 1,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexWrap: 'wrap',
  },
  titleFlex: {
    flexShrink: 1,
  },
  talentVariantTag: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 999,
    backgroundColor: 'rgba(251, 191, 36, 0.14)',
    borderWidth: 1,
    borderColor: 'rgba(251, 191, 36, 0.45)',
    flexShrink: 0,
  },
  talentVariantTagText: {
    color: '#fbbf24',
    fontSize: 8,
    fontWeight: '800',
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  bodyColumn: {
    flexGrow: 0,
    flexShrink: 1,
  },
  bodyScroll: {
    flexGrow: 0,
    flexShrink: 1,
    minHeight: 0,
  },
  bodyScrollContent: {
    flexGrow: 0,
    paddingBottom: 0,
  },
  descSection: {
    flex: 1,
    minHeight: 0,
  },
  mainScroll: {
    flex: 1,
    minHeight: 0,
    marginHorizontal: -2,
  },
  mainScrollContent: {
    paddingHorizontal: 2,
    paddingBottom: 4,
  },
  descScroll: {
    maxHeight: 108,
    marginHorizontal: -2,
  },
  descScrollMinimal: {
    maxHeight: 132,
    marginHorizontal: -2,
  },
  descScrollContent: {
    paddingHorizontal: 2,
    paddingVertical: 2,
  },
  statsSection: {
    marginTop: 4,
    flexShrink: 0,
  },
  levelAboveStatsRow: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    marginTop: 6,
    marginBottom: 2,
    gap: 3,
  },
  levelHintCallout: {
    alignSelf: 'stretch',
    marginTop: 2,
    marginBottom: 4,
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: 6,
    backgroundColor: 'rgba(125, 211, 252, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(125, 211, 252, 0.38)',
    borderLeftWidth: 3,
    borderLeftColor: UI_THEME.accentSky,
  },
  levelHintText: {
    color: '#bae6fd',
    fontSize: 10,
    lineHeight: 14,
    fontWeight: '600',
  },
  levelHintEmphasis: {
    color: '#fbbf24',
    fontWeight: '800',
  },
  levelHintBlock: {
    color: '#64748b',
    fontSize: 9,
    lineHeight: 13,
    maxWidth: '100%',
  },
  statsScroll: {
    maxHeight: 118,
    minHeight: 0,
  },
  statsScrollMinimal: {
    maxHeight: 72,
    minHeight: 0,
  },
  statsScrollContent: {
    paddingBottom: 0,
  },
  statsBlock: {
    paddingTop: 0,
  },
  statRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 6,
    paddingVertical: 1,
    borderBottomWidth: 1,
    borderBottomColor: UI_THEME.panelBorderMuted,
  },
  statRowLast: {
    borderBottomWidth: 0,
    paddingBottom: 0,
  },
  statLabel: {
    fontSize: 10,
    fontWeight: '600',
    flex: 1,
    minWidth: 0,
    paddingRight: 4,
    flexWrap: 'wrap',
  },
  statValueWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 4,
    maxWidth: '46%',
    flexShrink: 1,
    minWidth: 0,
  },
  statValue: {
    color: UI_THEME.textBright,
    fontSize: 10,
    fontWeight: '700',
    textAlign: 'right',
    flexShrink: 1,
    minWidth: 0,
    flexWrap: 'wrap',
  },
  statDelta: {
    color: UI_THEME.statDelta,
    fontSize: 9,
    fontWeight: '700',
    flexShrink: 0,
  },
  body: {
    color: UI_THEME.textBody,
    fontSize: 11,
    lineHeight: 15,
  },
});

const tip = kitAbilityTooltipModalStyles;

/** `app/data.jsx` StyleSheet keys → shared kit tooltip styles (Database god kit). */
export const kitAbilityTooltipStylesForData = {
  kitAbilityTooltipOverlayRoot: tip.overlayRoot,
  kitAbilityTooltipCardWrap: tip.cardWrap,
  kitAbilityTooltipCard: tip.card,
  kitAbilityTooltipHeader: tip.header,
  kitAbilityTooltipHeaderLeft: tip.headerLeft,
  kitAbilityTooltipIconWrap: tip.iconWrap,
  kitAbilityTooltipIcon: tip.icon,
  kitAbilityTooltipIconFallback: tip.iconFallback,
  kitAbilityTooltipIconFallbackText: tip.iconFallbackText,
  kitAbilityTooltipTitleWrap: tip.titleWrap,
  kitAbilityTooltipTitle: tip.title,
  kitAbilityTooltipSubTitle: tip.subTitle,
  kitAbilityTooltipHeaderRight: tip.headerRight,
  kitAbilityTooltipCloseCornerBtn: tip.closeCornerBtn,
  kitAbilityTooltipCloseCornerText: tip.closeCornerText,
  kitAbilitySectionLabel: tip.sectionLabel,
  kitAbilityLevelStepperTopRight: tip.levelStepperTopRight,
  kitAbilityLevelStepperBtn: tip.levelStepperBtn,
  kitAbilityLevelStepperText: tip.levelStepperText,
  kitAbilityLevelStepperTextDisabled: tip.levelStepperTextDisabled,
  kitAbilityLevelCurrentText: tip.levelCurrentText,
  kitAbilityDescSection: tip.descSection,
  kitAbilityBodyColumn: tip.bodyColumn,
  kitAbilityMainScroll: tip.mainScroll,
  kitAbilityMainScrollContent: tip.mainScrollContent,
  kitAbilityDescScroll: tip.descScroll,
  kitAbilityDescScrollContent: tip.descScrollContent,
  kitAbilityStatsSection: tip.statsSection,
  kitAbilityTooltipScroll: tip.statsScroll,
  kitAbilityStatsScrollContent: tip.statsScrollContent,
  kitAbilityStatsBlock: tip.statsBlock,
  kitAbilityStatRow: tip.statRow,
  kitAbilityStatRowLast: tip.statRowLast,
  kitAbilityStatLabel: tip.statLabel,
  kitAbilityStatValueWrap: tip.statValueWrap,
  kitAbilityStatValue: tip.statValue,
  kitAbilityStatDelta: tip.statDelta,
  kitAbilityTooltipBody: tip.body,
};

/** Simple centered modal chrome (patch badges, item/god icon tooltips). */
export const genericTooltipChromeStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: UI_THEME.overlayScrim,
    justifyContent: 'center',
    alignItems: 'center',
  },
  content: {
    backgroundColor: UI_THEME.panelBgSection,
    paddingHorizontal: 20,
    paddingVertical: 16,
    paddingRight: 40,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: UI_THEME.panelBorder,
    maxWidth: 300,
    ...UI_THEME.shadowCard,
    position: 'relative',
  },
  text: {
    color: UI_THEME.textDropdown,
    fontSize: 14,
    lineHeight: 20,
  },
  closeButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: UI_THEME.panelBorder,
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeText: {
    color: UI_THEME.textClose,
    fontSize: 16,
    fontWeight: '700',
  },
});

/** Legacy StyleSheet keys used in `app/index.jsx` and Database pages. */
export const genericTooltipStylesForApp = {
  tooltipOverlay: genericTooltipChromeStyles.overlay,
  tooltipContent: genericTooltipChromeStyles.content,
  tooltipText: genericTooltipChromeStyles.text,
  tooltipCloseButton: genericTooltipChromeStyles.closeButton,
  tooltipCloseText: genericTooltipChromeStyles.closeText,
};

/** Mechanics / counterplay detail tooltips (wider card, same chrome). */
export const counterplayTooltipChromeStyles = StyleSheet.create({
  content: {
    backgroundColor: UI_THEME.panelBgSection,
    paddingHorizontal: 20,
    paddingVertical: 16,
    paddingRight: 40,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: UI_THEME.panelBorder,
    maxWidth: 400,
    ...UI_THEME.shadowCard,
    position: 'relative',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  titleContainer: {
    flex: 1,
    marginLeft: 12,
  },
  title: {
    color: UI_THEME.textBright,
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 4,
  },
  subtitle: {
    color: UI_THEME.textMuted,
    fontSize: 14,
    fontWeight: '600',
  },
  icon: {
    width: 48,
    height: 48,
    borderRadius: UI_THEME.radiusPanel,
  },
  body: {
    color: UI_THEME.textDropdown,
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 8,
  },
  stat: {
    color: UI_THEME.accentSky,
    fontSize: 14,
    fontWeight: '600',
    marginTop: 8,
  },
});

const cp = counterplayTooltipChromeStyles;

export const counterplayTooltipStylesForData = {
  counterplayTooltipContent: cp.content,
  counterplayTooltipHeader: cp.header,
  counterplayTooltipTitleContainer: cp.titleContainer,
  counterplayTooltipTitle: cp.title,
  counterplayTooltipSubtitle: cp.subtitle,
  counterplayTooltipIcon: cp.icon,
  counterplayTooltipText: cp.body,
  counterplayTooltipStat: cp.stat,
};
