const SCRIPT_CONFIG = {
  REQUIRED_SUPABASE_ENV_VARS: [
    'EXPO_PUBLIC_SUPABASE_URL',
    'EXPO_PUBLIC_SUPABASE_KEY',
  ],
  OUTPUT: {
    DIVIDER_WIDTH: 60,
    PREVIEW_LENGTH: 20,
  },
};

module.exports = SCRIPT_CONFIG;
